/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package westen;

/**
 *
 * @author santi
 */
public class RoomsEX {    
    public static void main(String args[]) throws Exception
    {
        String roomsFolder = "data/rooms/";
                                
        Rooms.generateMapData(roomsFolder, 
                        new String[]{"part1/room0",
                                     "part1/room1",
                                     "part1/room2-lobby",
                                     "part1/room3",
                                     "part1/room4",
                                     "part1/room5-dining",
                                     "part1/room6",
                                     "part1/room7-library",
                                     "part1/room8-kitchen",
                                     "part1/room9-storage",
                                     "part1/room10",
                                     "part1/room11-backyard"}, 
                        "src/autogenerated/map1");
        
        Rooms.generateMapData(roomsFolder, 
                        new String[]{"part2/room16",
                                     "part2/room17-music",
                                     "part2/room18-bath",
                                     "part2/room19",
                                     "part2/room20-writing",
                                     "part2/room21",
                                     "part2/room22-closet",
                                     "part2/room23",
                                     "part2/room24-ritual"}, 
                        "src/autogenerated/map2");        

        Rooms.generateMapData(roomsFolder, 
                        new String[]{"part3/room32",
                                     "part3/room33",
                                     "part3/room34",
                                     "part3/room35-vampire1",
                                     "part3/room36",
                                     "part3/room37",
                                     "part3/room38",
                                     "part3/room39",
                                     "part3/room40-chapel",
                                     "part3/room41",
                                     "part3/room42-vampire3",
                                     "part3/room43-workshop",
                                     "part3/room44-feeding",
                                     "part3/room45-vampire2",
                                     "part3/room46"}, 
                        "src/autogenerated/map3"); 
        
        Rooms.generateMapData(roomsFolder, 
                        new String[]{"part4/room48",
                                     "part4/room49",
                                     "part4/room50",
                                     "part4/room51-bath",
                                     "part4/room52-bedroom1",
                                     "part4/room53-bedroom2",
                                     "part4/room54-bedroom3",
                                     "part4/room55-bath",
                                     "part4/room56-bedroom4",
                                     "part4/room57-bath",
                                     "part4/room58-bedroom5",
                                     "part4/room59-bath",
                                     "part4/room60",
                                     "part4/room61-lab"}, 
                        "src/autogenerated/map4");   
        
        Rooms.generateMapData(roomsFolder, 
                        new String[]{"part5/room64-intro",
                                     "part5/room65-living",
                                     "part5/room66-kitchen",
                                     "part5/room67-bedroom",
                                     "part5/room68-bath",
                                     "part5/room69-street",
                                     "part5/room70-alley",
                                     "part5/room71-street3",
                                     "part5/room72-bookstore"},
                        "src/autogenerated/map5");

        Rooms.generateMapData(roomsFolder, 
                        new String[]{"part6/room80-ossuary",
                                     "part6/room81",
                                     "part6/room82-statue",
                                     "part6/room83",
                                     "part6/room84-livingroom",
                                     "part6/room85-bedroom1",
                                     "part6/room86-bedroom2",
                                     "part6/room87-hidden-chapel",
                                     "part6/room88-vlad-quarters",
                                     "part6/room89-prison-entrance",
                                     "part6/room90-prison1",
                                     "part6/room91-prison2",
                                     "part6/room92-mini-boss",
                                     "part6/room93-secret-boss",
                                     "part6/room94-passage",
                                     "part6/room95-passage",
                        
                        },
                        "src/autogenerated/map6");
        
    }    
}
