/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package westen;

import PNGtoMSX.ConvertPatternsToAssembler;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import util.Z80Assembler;
import util.ZX0Wrapper;

/**
 *
 * @author santi
 */
public class SpritesEX {
    public static int TOLERANCE = 64;
    
    public static void main(String args[]) throws Exception
    {
        Sprites.main(args);

        {
            String inputImageFileName = "data/tiled-rooms/tiles.png";
            String outputFileName = "src/autogenerated/object-sprites";

            ConvertPatternsToAssembler.MSX1Palette = Walls.MSX1Palette;

            BufferedImage img = ImageIO.read(new File(inputImageFileName));
            List<Integer> data = new ArrayList<>();

            Sprites.getSpriteWithColor(8, 0, img, 10, data);
            Sprites.getSpriteWithColor(24, 0, img, 10, data);
            Sprites.getSpriteWithColor(40, 0, img, 15, data);
            Sprites.getSpriteWithColor(56, 0, img, 5, data);
            Sprites.getSpriteWithColor(72, 0, img, 11, data);

            System.out.println("dataEX: " + data.size());
            System.out.println("spritesEX: " + data.size()/32);

            Z80Assembler.dataToBinary(data, outputFileName+".bin");    
            ZX0Wrapper.main(outputFileName+".bin", outputFileName+".zx0", true, false);        
        }        
        
        // Lucy in chapel cutscene:
        {
            String playerImageFileName = "data/player-beard.png";
            String outputFileName = "src/autogenerated/cutscene-lucy-sprites";
        
            ConvertPatternsToAssembler.MSX1Palette = Walls.MSX1Palette;
        
            BufferedImage img = ImageIO.read(new File(playerImageFileName));
        
            List<Integer> data = new ArrayList<>();
            
            Sprites.generateLucyFrameData(128, 32, img, data);
            Sprites.generateLucyFrameData(144, 32, img, data);
            Sprites.generateLucyFrameData(160, 32, img, data);

            Sprites.generateLucyFrameData(128, 96, img, data);
            Sprites.generateLucyFrameData(144, 96, img, data);
            Sprites.generateLucyFrameData(160, 96, img, data);

            Sprites.generateLucyFrameData(192, 96, img, data);
            
            System.out.println("data: " + data.size());
            System.out.println("sprites: " + data.size()/32);

            Z80Assembler.dataToBinary(data, outputFileName+".bin");    
            ZX0Wrapper.main(outputFileName+".bin", outputFileName+".zx0", true, false);
        }        
    }
 
}
