/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package westen;

import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import text.EncodeText;
import text.PAKFont;
import util.Pair;

/**
 *
 * @author santi
 */
public class TextES {
    public static PAKFont font = null;
    
    public static void main(String args[]) throws Exception
    {
        generateTextData(true);
    }
    
    
    public static PAKFont setESFont() throws Exception
    {
        List<String> characters = new ArrayList<>();
        characters.add(" !/@'()?,-.");
        characters.add("0123456789:");
        characters.add("ABCDEFGHIJKLMNO");
        characters.add("PQRSTUVWXYZ");
        characters.add("abcdefghijklmno");
        characters.add("pqrstuvwxyzáéíóú");
        characters.add("ñÉ¡¿");
        font = new PAKFont("data/font-es.png", characters);
        return font;
    }


    public static void generateTextData(boolean ex) throws Exception
    {
        font = setESFont();
        font.generateAssemblerData("src/autogenerated/font-es");
        
        font.printFontInfo();
                
        // Text lines:
        List<String> lines = new ArrayList<>();
        
        HashMap<String,String> lines_with_constant = new HashMap<>();
//        addLineSafe(lines_with_constant, "BRAIN GAMES", "BRAIN_GAMES");
        addLineSafe(lines_with_constant, "Presenta", "PRESENTS", 8);

        addLineSafe(lines_with_constant, "Londres, 1898", "INTRO_MSG1", 8);
        addLineSafe(lines_with_constant, "¡Ding dong!", "INTRO_MSG2", 8);
        addLineSafe(lines_with_constant, "¡Ya voy!", "INTRO_MSG3", 8);
        addLineSafe(lines_with_constant, "Carta para usted, profesor", "INTRO_MSG4", 16);
        addLineSafe(lines_with_constant, "¡Gracias Richard!", "INTRO_MSG5", 12);
        addLineSafe(lines_with_constant, "¡A ver qué dice!", "INTRO_MSG6", 16);
        addLineSafe(lines_with_constant, "¡Malísimas noticias!", "INTRO_MSG7", 12);
        addLineSafe(lines_with_constant, "¡JW era un gran amigo!", "INTRO_MSG8", 12);
        addLineSafe(lines_with_constant, "¡Debo ir de inmediato!", "INTRO_MSG9", 14);
        
        addLineSafe(lines_with_constant, "Querido Profesor Edward Kelvin:","LETTER1_LINE1", 28);
        addLineSafe(lines_with_constant, "Nos apena informarle de la muerte de Jonathan","LETTER1_LINE2", 28);
        addLineSafe(lines_with_constant, "Westen, fallecido el 16 de octubre. En su voluntad,","LETTER1_LINE3", 28);
        addLineSafe(lines_with_constant, "el Sr. Westen le dejó su cuaderno científico. Y","LETTER1_LINE4", 28);
        addLineSafe(lines_with_constant, "también una carta, que le adjuntamos aquí.","LETTER1_LINE5", 28);
        addLineSafe(lines_with_constant, "Le informamos también de que la Sra. Lucy Westen","LETTER1_LINE6", 28);
        addLineSafe(lines_with_constant, "tomará posesión de la casa el 1 de diciembre.","LETTER1_LINE7", 28);
        
        if (ex) {
            addLineSafe(lines_with_constant, "Si está leyendo esto, probablemente estoy","LETTER2_LINE2", 24);
            addLineSafe(lines_with_constant, "muerto. Debe encontrar mi cuaderno antes","LETTER2_LINE3", 24);
            addLineSafe(lines_with_constant, "de que mi hermana Lucy tome posesión de la","LETTER2_LINE4", 24);
            addLineSafe(lines_with_constant, "casa en Purfleet. ¡Solo usted es capaz de","LETTER2_LINE5", 24);
            addLineSafe(lines_with_constant, "comprenderlo! Le adjunto la llave de la","LETTER2_LINE6", 24);
            addLineSafe(lines_with_constant, "mansión Westen, y parte de una llave que le","LETTER2_LINE7", 24);
            addLineSafe(lines_with_constant, "será necesaria para llegar a mi laboratorio.","LETTER2_LINE8", 24);
            addLineSafe(lines_with_constant, "Por favor, es importante para mí.","LETTER2_LINE9", 24);
        } else {
            addLineSafe(lines_with_constant, "Si está leyendo esto, probablemente estoy","LETTER2_LINE2", 24);
            addLineSafe(lines_with_constant, "muerto. Debe encontrar mi cuaderno antes","LETTER2_LINE3", 24);
            addLineSafe(lines_with_constant, "de que mi hermana Lucy tome posesión de la","LETTER2_LINE4", 24);
            addLineSafe(lines_with_constant, "casa. ¡Solo usted es capaz de comprenderlo!","LETTER2_LINE5", 24);
            addLineSafe(lines_with_constant, "Le adjunto la llave de la mansión Westen,","LETTER2_LINE6", 24);
            addLineSafe(lines_with_constant, "y parte de una llave que le será necesaria","LETTER2_LINE7", 24);
            addLineSafe(lines_with_constant, "para llegar a mi laboratorio. Por favor, es","LETTER2_LINE8", 24);
            addLineSafe(lines_with_constant, "importante para mí.","LETTER2_LINE9", 24);
        }
        
        addLineSafe(lines_with_constant, "Combinación: 15-30-10", "LETTER3_LINE1_SECRET", 12);
        addLineSafe(lines_with_constant, "Querido Ed:", "LETTER3_LINE1", 22);
        addLineSafe(lines_with_constant, "Espero que encuentre esto antes que mi", "LETTER3_LINE2", 22);
        addLineSafe(lines_with_constant, "familia. Contiene la clave que le llevará", "LETTER3_LINE3", 22);
        addLineSafe(lines_with_constant, "a la otra mitad de la llave que tiene.", "LETTER3_LINE4", 22);
        addLineSafe(lines_with_constant, "Usé tinta de limón. Usted sabrá qué", "LETTER3_LINE5", 22);
        addLineSafe(lines_with_constant, "hacer. Pronto entenderá la prudencia.", "LETTER3_LINE6", 22);
        addLineSafe(lines_with_constant, "JW", "LETTER3_LINE7", 22);
        
//        addLineSafe(lines_with_constant, "Querido Ed,", "LETTER4_LINE1");
        addLineSafe(lines_with_constant, "Ahora que ha visto la casa con sus propios", "LETTER4_LINE2", 24);
        addLineSafe(lines_with_constant, "ojos, quizás ya se haya dado cuenta. Mi", "LETTER4_LINE3", 24);
        addLineSafe(lines_with_constant, "apellido no es Westen, es Westenra.", "LETTER4_LINE4", 24);
        addLineSafe(lines_with_constant, "Ocultamos nuestro nombre para proteger a", "LETTER4_LINE5", 24);
        addLineSafe(lines_with_constant, "mi hermana. Como recordará, Lucy Westenra", "LETTER4_LINE6", 24);
        addLineSafe(lines_with_constant, "sufrió un horrible accidente dos años atrás", "LETTER4_LINE7", 24);
        addLineSafe(lines_with_constant, "en un encuentro con una criatura a la que", "LETTER4_LINE8", 24);
        addLineSafe(lines_with_constant, "llaman vampiro. ¡Ed, son todos vampiros!", "LETTER4_LINE9", 24);
        addLineSafe(lines_with_constant, "No murió tal como se informó... y no está", "LETTER4_LINE10", 24);
        addLineSafe(lines_with_constant, "sola. ¡Pero tengo un plan! ¡Sé cómo matarlos!", "LETTER4_LINE11", 24);
        addLineSafe(lines_with_constant, "Busque sus ataúdes, allí es donde duermen.", "LETTER4_LINE12", 24);
        addLineSafe(lines_with_constant, "Frótelos con ajo antes de que lleguen", "LETTER4_LINE13", 24);
        addLineSafe(lines_with_constant, "y así morirán mientras duermen. ¡Pero", "LETTER4_LINE14", 24);
        addLineSafe(lines_with_constant, "apresúrese! ¡Prepárelo antes de que lleguen!", "LETTER4_LINE15", 24);
        addLineSafe(lines_with_constant, "Si se demora, matarlos será más difícil.", "LETTER4_LINE16", 24);
        addLineSafe(lines_with_constant, "Deberá clavar una estaca frotada con ajo", "LETTER4_LINE17", 24);
        addLineSafe(lines_with_constant, "en su corazón, mientras duermen.", "LETTER4_LINE18", 24);
        addLineSafe(lines_with_constant, "Espero que no deba recurrir a ese método...", "LETTER4_LINE19", 24);
        addLineSafe(lines_with_constant, "¡Le deseo suerte! JW", "LETTER4_LINE20", 24);

        addLineSafe(lines_with_constant, "P.S.:", "LETTER5_LINE0", 24);
        addLineSafe(lines_with_constant, "Los vampiros de mi familia duermen en", "LETTER5_LINE1", 24);
        addLineSafe(lines_with_constant, "ataúdes en el sótano. Vi que usan", "LETTER5_LINE2", 24);
        addLineSafe(lines_with_constant, "cerraduras de combinación en las puertas.", "LETTER5_LINE3", 24);
        addLineSafe(lines_with_constant, "Creo que usaron sus nombres vampíricos", "LETTER5_LINE4", 24);
        addLineSafe(lines_with_constant, "como claves. Mantienen sus nombres", "LETTER5_LINE5", 24);
        addLineSafe(lines_with_constant, "en secreto, pero quizás haya pistas", "LETTER5_LINE6", 24);
        addLineSafe(lines_with_constant, "en sus diarios y otros escritos que", "LETTER5_LINE7", 24);
        addLineSafe(lines_with_constant, "pueda encontrar en la casa.", "LETTER5_LINE8", 24);

        addLineSafe(lines_with_constant, "Diario de John Seward.", "DIARY1_LINE1", 24);
        addLineSafe(lines_with_constant, "...", "DIARY1_LINE2", 24);
        addLineSafe(lines_with_constant, "7 de julio, 1897", "DIARY1_LINE3", 24);
        addLineSafe(lines_with_constant, "¡Lucy al fin me hizo parte de su círculo!", "DIARY1_LINE4", 24);
        addLineSafe(lines_with_constant, "Para recordar esta ocasión usaré el", "DIARY1_LINE5", 24);
        addLineSafe(lines_with_constant, "nombre de este mes como el mío propio.", "DIARY1_LINE6", 24);

        addLineSafe(lines_with_constant, "Diario de Arthur Holmwood.", "DIARY2_LINE1", 24);
        addLineSafe(lines_with_constant, "26 de junio, 1897", "DIARY2_LINE3", 24);
        addLineSafe(lines_with_constant, "Mi amada por fin me ha convertido. Estoy", "DIARY2_LINE4", 24);
        addLineSafe(lines_with_constant, "en éxtasis. Ahora necesito escoger nombre.", "DIARY2_LINE5", 24);
        addLineSafe(lines_with_constant, "Usaré su apellido para demostrarle mi", "DIARY2_LINE6", 24);
        addLineSafe(lines_with_constant, "devoción.", "DIARY2_LINE7", 24);

        addLineSafe(lines_with_constant, "ESPACIO para empezar", "START", 16);
        addLineSafe(lines_with_constant, "M para instrucciones", "CONTROLS", 16);

        addLineSafe(lines_with_constant, "Game Over", "GAME_OVER", 8);

        addLineSafe(lines_with_constant, "Joystick / cursores: caminar.", "TUTORIAL1_LINE1", 17);
        addLineSafe(lines_with_constant, "Botón 1 / espacio: saltar.", "TUTORIAL1_LINE2", 17);
        addLineSafe(lines_with_constant, "Q cambia mapeo de direcciones.", "TUTORIAL1_LINE3", 17);

        addLineSafe(lines_with_constant, "Mientras pulsas el botón 2 / M:", "TUTORIAL2_LINE1", 18);
        addLineSafe(lines_with_constant, "- Joystick / cursores para", "TUTORIAL2_LINE2", 18);
        addLineSafe(lines_with_constant, "  moverte por el inventario,", "TUTORIAL2_LINE3", 18);
        addLineSafe(lines_with_constant, "- Botón 1 / espacio para usar.", "TUTORIAL2_LINE4", 18);

        addLineSafe(lines_with_constant, "Empuja objetos caminando", "TUTORIAL3_LINE1", 17);
        addLineSafe(lines_with_constant, "contra ellos.", "TUTORIAL3_LINE2", 17);

        addLineSafe(lines_with_constant, "Para interactuar con objetos: con", "TUTORIAL4_LINE1", 20);
        addLineSafe(lines_with_constant, "un hueco vacío en el inventario", "TUTORIAL4_LINE2", 20);
        addLineSafe(lines_with_constant, "seleccionado, pulsa Botón 1 / espacio", "TUTORIAL4_LINE3", 20);
        addLineSafe(lines_with_constant, "mientras presionas el botón 2 / M.", "TUTORIAL4_LINE4", 20);
        addLineSafe(lines_with_constant, "Para cogerlos: haz lo mismo mientras", "TUTORIAL4_LINE5", 20);
        addLineSafe(lines_with_constant, "estás encima del objeto.", "TUTORIAL4_LINE6", 20);

        if (ex) {
            addLineSafe(lines_with_constant, "Brain Games (2022)", "CREDITS1", 24);
            addLineSafe(lines_with_constant, "Código/Gráficos: Santiago Ontañón", "CREDITS2", 24);
            addLineSafe(lines_with_constant, "Música/SFX: Gryzor87    Portada: Sirelion", "CREDITS3", 24);

            addLineSafe(lines_with_constant, "¡Podría llegar a la estación esta", "GAME_START_MESSSAGE1", 19);
            addLineSafe(lines_with_constant, "noche si me doy prisa! Solo necesito", "GAME_START_MESSSAGE2", 19);        
            addLineSafe(lines_with_constant, "mi equipaje.", "GAME_START_MESSSAGE3", 19);        

            addLineSafe(lines_with_constant, "¡Necesito mi equipaje primero!", "NEED_LUGGAGE", 19);        

            addLineSafe(lines_with_constant, "Acabo de llegar a la mansión Westen.", "HOUSE_ARRIVAL_MESSSAGE1", 19);
            addLineSafe(lines_with_constant, "Ahora, ¡a buscar las notas de JW!", "HOUSE_ARRIVAL_MESSSAGE2", 19);
        } else {
            addLineSafe(lines_with_constant, "Santiago Ontañón 2021", "CREDITS", 16);

            addLineSafe(lines_with_constant, "Acabo de llegar a la mansión Westen.", "GAME_START_MESSSAGE1", 19);
            addLineSafe(lines_with_constant, "Ahora, ¡a buscar las notas de JW!", "GAME_START_MESSSAGE2", 19);
        }        
        
        addLineSafe(lines_with_constant, "Dejaré los taburetes.", "DROP_STOOLS", 19);
        addLineSafe(lines_with_constant, "¡Una nota de JW! ¡Vamos a leerla!", "LETTER3", 19);

        addLineSafe(lines_with_constant, "Nada que usar por aquí.", "USE_ERROR", 19);
        addLineSafe(lines_with_constant, "No veo la cerradura adecuada.", "ITEM_KEY", 19);
        addLineSafe(lines_with_constant, "Parece la llave de un baúl.", "ITEM_KEY_GUN", 19);
        addLineSafe(lines_with_constant, "Debo encontar la otra mitad.", "ITEM_HALF_KEY", 19);
        addLineSafe(lines_with_constant, "Una botella de aceite de lámparas.", "ITEM_OIL", 19);
        addLineSafe(lines_with_constant, "Rellenaré la lámpara con el aceite.", "ITEM_OIL_USED", 19);
        addLineSafe(lines_with_constant, "Una lámpara de aceite. Está vacía.", "ITEM_LAMP", 19);
        addLineSafe(lines_with_constant, "Una lámpara de aceite encendida.", "ITEM_LAMP_ON", 19);
        addLineSafe(lines_with_constant, "¡El calor de la lámpara ha revelado", "USE_LAMP1", 19);
        addLineSafe(lines_with_constant, "la tinta de limón en la carta!", "USE_LAMP2", 19);
        addLineSafe(lines_with_constant, "No hay nada tras este cuadro.", "USE_PAINTING", 19);
        addLineSafe(lines_with_constant, "¡Una caja fuerte tras el cuadro!", "USE_PAINTING_SAFE", 19);
        addLineSafe(lines_with_constant, "No sé la combinación.", "USE_SAFE", 19);
        addLineSafe(lines_with_constant, "¡La clave de la carta ha funcionado!", "USE_SAFE_OPEN1", 19);
        addLineSafe(lines_with_constant, "No hay nada más dentro.", "USE_SAFE_OPEN2", 19);
        addLineSafe(lines_with_constant, "¡Las dos mitades encajan!", "MERGE_RED_KEY", 19);
        addLineSafe(lines_with_constant, "Hay una página suelta.", "USE_BOOK", 19);
        addLineSafe(lines_with_constant, "No quiero dejar la vela aquí.", "USE_CANDLE", 19);
        addLineSafe(lines_with_constant, "Quincey Morris, 1862 - 1897", "USE_TOMBSTONE", 19);
        addLineSafe(lines_with_constant, "Está cerrada con llave.", "USE_DOOR", 19);
        addLineSafe(lines_with_constant, "Muchos libros de ocultismo.", "USE_BOOK_STACK", 19);
        addLineSafe(lines_with_constant, "Este baúl parece decorativo.", "USE_CHEST", 19);
        addLineSafe(lines_with_constant, "No necesito ir ahora mismo.", "USE_TOILET", 19);
        addLineSafe(lines_with_constant, "¡No tengo tiempo para baños!", "USE_BATHTUB", 19);
        addLineSafe(lines_with_constant, "Un gramófono precioso.", "USE_GRAMOPHONE", 19);
        addLineSafe(lines_with_constant, "Un violín. No sé tocarlo.", "USE_VIOLIN", 19);
        addLineSafe(lines_with_constant, "No necesito lavarme las manos.", "USE_SINK", 19);
        addLineSafe(lines_with_constant, "Esta ventana no se abre.", "USE_WINDOW", 19);
        addLineSafe(lines_with_constant, "Un ataud impresionante.", "USE_COFFIN", 19);
        addLineSafe(lines_with_constant, "¡Esto son restos humanos!", "USE_BONES", 19);  
        addLineSafe(lines_with_constant, "Este baúl está cerrado.", "USE_CHEST_GUN1", 19);
        addLineSafe(lines_with_constant, "No hay nada más en el baúl.", "USE_CHEST_GUN2", 19);
        addLineSafe(lines_with_constant, "La llave ha abierto el baúl.", "TAKE_GUN1", 19);
        addLineSafe(lines_with_constant, "¡Había un revólver dentro!", "TAKE_GUN2", 19);

        addLineSafe(lines_with_constant, "Un libro de finanzas. Pero qué raro,", "USE_BOOK_WESTENRA1", 19);
        addLineSafe(lines_with_constant, "en lugar de Westen, estas son las", "USE_BOOK_WESTENRA2", 19);
        addLineSafe(lines_with_constant, "finanzas de la familia Westenra...", "USE_BOOK_WESTENRA3", 19);

        addLineSafe(lines_with_constant, "El diario de Lucy Westenra. La ma-", "USE_DIARY3_1", 19);
        addLineSafe(lines_with_constant, "yoría de páginas están arrancadas,", "USE_DIARY3_2", 19);
        addLineSafe(lines_with_constant, "pero había una llave dentro.", "USE_DIARY3_3", 19);
        
        addLineSafe(lines_with_constant, "¡Lucy Westen es Lucy Westenra!", "USE_LAB_NOTES_1", 19);
        addLineSafe(lines_with_constant, "¡Esto es peor de lo que imaginaba!", "USE_LAB_NOTES_2", 19);
        addLineSafe(lines_with_constant, "¡Debo darme prisa y encontrar ajo!", "USE_LAB_NOTES_3", 19);

        addLineSafe(lines_with_constant, "Esta caja parece bastante floja...", "USE_BREAKABLE_CRATE", 19);
        addLineSafe(lines_with_constant, "Nada que pueda romper cerca.", "USE_HAMMER1", 19);
        addLineSafe(lines_with_constant, "¡He roto la caja con el martillo!", "USE_HAMMER2", 19);
        addLineSafe(lines_with_constant, "Una cabeza de ajo.", "USE_GARLIC1", 19);
        addLineSafe(lines_with_constant, "He frotado el ajo en la estaca.", "USE_GARLIC2", 19);
        addLineSafe(lines_with_constant, "Una estaca de madera.", "USE_STAKE", 19);
        addLineSafe(lines_with_constant, "Una estaca de madera con ajo.", "USE_RUBBED_STAKE", 19);
        addLineSafe(lines_with_constant, "¡Ahora no! ¡El vampiro está alerta!", "USE_RUBBED_STAKE_AWAKE", 19);
        addLineSafe(lines_with_constant, "¡Debo acercarme más!", "USE_RUBBED_STAKE_TOO_FAR", 19);
        addLineSafe(lines_with_constant, "¡Ha funcionado! ¡Ha muerto!", "USE_RUBBED_STAKE_KILL", 19);
        addLineSafe(lines_with_constant, "Hay una cerradura de combinación.", "USE_VAMPIRE_DOOR", 19);
        addLineSafe(lines_with_constant, "¡Qué raro! Esta parte de la casa", "MSG_ABANDONED1", 19);
        addLineSafe(lines_with_constant, "parece abandonada...", "MSG_ABANDONED2", 19);

        addLineSafe(lines_with_constant, "¡Esta habitación está llena de", "MSG_BOOKS1", 19);
        addLineSafe(lines_with_constant, "libros de las artes oscuras!", "MSG_BOOKS2", 19);
        addLineSafe(lines_with_constant, "¿Por qué los tendría JW?", "MSG_BOOKS3", 19);
        addLineSafe(lines_with_constant, "¿Qué es esto? ¿Celebraba JW", "MSG_PENTAGRAM1", 19);
        addLineSafe(lines_with_constant, "rituales demoníacos?", "MSG_PENTAGRAM2", 19);

        addLineSafe(lines_with_constant, "¡La puerta se ha abierto! Creía que", "MSG_PENTAGRAM_SOLVED1", 19);
        addLineSafe(lines_with_constant, "solo buscaba las notas de JW, ¡pero", "MSG_PENTAGRAM_SOLVED2", 19);
        addLineSafe(lines_with_constant, "aquí hay más de lo que parece!", "MSG_PENTAGRAM_SOLVED3", 19);
        addLineSafe(lines_with_constant, "¡Restos humanos!", "MSG_FEEDING1", 19);
        addLineSafe(lines_with_constant, "Vale, ¡ahora sí que está claro que", "MSG_FEEDING2", 19);
        addLineSafe(lines_with_constant, "algo macabro ocurre en esta casa!", "MSG_FEEDING3", 19);
        addLineSafe(lines_with_constant, "¡Por fin! ¡El laboratorio de JW!", "MSG_LAB", 19);

        addLineSafe(lines_with_constant, "¡Oigo ruidos en la entrada!", "MSG_FAMILY_CUTSCENE1", 19);
        addLineSafe(lines_with_constant, "Arthur: ¡Por fin! ¡Ese hermano tuyo está muerto!", "MSG_FAMILY_CUTSCENE2", 31);
        addLineSafe(lines_with_constant, "Lucy: ¡Sí! ¡La casa es ahora mía!", "MSG_FAMILY_CUTSCENE3", 31);
        addLineSafe(lines_with_constant, "Lucy: ¡Ansiaba ya entrar en mi sótano en paz!", "MSG_FAMILY_CUTSCENE4", 31);
        addLineSafe(lines_with_constant, "Lucy: ¡¡En esta casa construiremos nuestra familia!!", "MSG_FAMILY_CUTSCENE5", 31);
        addLineSafe(lines_with_constant, "Lucy: ¡Hoy somos solo nosotros pero mañana seremos más!", "MSG_FAMILY_CUTSCENE6", 31);
        addLineSafe(lines_with_constant, "Lucy: Jajaja", "MSG_FAMILY_CUTSCENE7A", 31);
        addLineSafe(lines_with_constant, "John: Jajaja", "MSG_FAMILY_CUTSCENE7B", 31);
        addLineSafe(lines_with_constant, "Arthur: Jajaja", "MSG_FAMILY_CUTSCENE7C", 31);
        addLineSafe(lines_with_constant, "Lucy: Pero hoy descansaremos. ¡Vamos!", "MSG_FAMILY_CUTSCENE8", 31);

        addLineSafe(lines_with_constant, "¡No creo lo que veo!", "MSG_FAMILY_CUTSCENE9", 19);
        addLineSafe(lines_with_constant, "¡Ya están aquí! He sido muy lento.", "MSG_FAMILY_CUTSCENE10", 19);
        addLineSafe(lines_with_constant, "Tendré que usar las estacas...", "MSG_FAMILY_CUTSCENE11", 19);

        addLineSafe(lines_with_constant, "¡Se ha abierto!", "OPEN_VAMPIRE1_DOOR", 19);
        addLineSafe(lines_with_constant, "Ya no necesito este diario...", "OPEN_VAMPIRE1_DOOR2", 19);
        addLineSafe(lines_with_constant, "¡Un vampiro!", "ENTER_VAMPIRE_ROOM1", 19);
        addLineSafe(lines_with_constant, "Me acercaré mientras duerme...", "ENTER_VAMPIRE_ROOM2", 19);

        addLineSafe(lines_with_constant, "¡Esta debe ser Lucy!", "ENTER_VAMPIRE3_ROOM1", 19);
        addLineSafe(lines_with_constant, "¡Lo conseguí! ¡Lucy está muerta!", "ENTER_VAMPIRE3_ROOM2", 19);
        addLineSafe(lines_with_constant, "Había una nota en el cadáver.", "FIND_VAMPIRE_NOTE", 19);
        
        
        addLineSafe(lines_with_constant, "Tareas de John Seward:", "VAMPIRE1_NOTE1", 24);
        addLineSafe(lines_with_constant, "- Matar a JW (hecho)", "VAMPIRE1_NOTE2", 24);
        addLineSafe(lines_with_constant, "- Encontrar mi diario", "VAMPIRE1_NOTE3", 24);
        addLineSafe(lines_with_constant, "- Agradecer a Lucy por usar nuestras ini-", "VAMPIRE1_NOTE4", 24);
        addLineSafe(lines_with_constant, "  ciales para formar su nombre vampírico.", "VAMPIRE1_NOTE5", 24);
        addLineSafe(lines_with_constant, "  ¡Qué honor para nosotros tres!", "VAMPIRE1_NOTE6", 24);

        addLineSafe(lines_with_constant, "Lucy, ¿por qué tuviste que usar las ini-", "VAMPIRE2_NOTE1", 22);
        addLineSafe(lines_with_constant, "ciales de esos dos? ¡YO soy tu marido!", "VAMPIRE2_NOTE2", 22);        
        addLineSafe(lines_with_constant, "Al menos usaste las mías primero...", "VAMPIRE2_NOTE3", 22);
        addLineSafe(lines_with_constant, "Arthur Holmwood", "VAMPIRE2_NOTE4", 22);

        addLineSafe(lines_with_constant, "2 de diciembre, 1898", "ENDING_LINE1", 17);
        addLineSafe(lines_with_constant, "Aún no sé cómo sentirme acerca", "ENDING_LINE2", 17);
        addLineSafe(lines_with_constant, "de los eventos que sucedieron", "ENDING_LINE3", 17);
        addLineSafe(lines_with_constant, "en la mansión Westen..., digo", "ENDING_LINE4", 17);
        addLineSafe(lines_with_constant, "Westenra.", "ENDING_LINE5", 17);

        addLineSafe(lines_with_constant, "Aunque me alivia haber liberado", "ENDING_LINE6", 17);
        addLineSafe(lines_with_constant, "al mundo de esas bestias y", "ENDING_LINE7", 17);
        addLineSafe(lines_with_constant, "seguir con vida, me entristece", "ENDING_LINE8", 17);
        addLineSafe(lines_with_constant, "saber que la vida de mi buen", "ENDING_LINE9", 17);
        addLineSafe(lines_with_constant, "amigo terminó por culpa de", "ENDING_LINE10", 17);
        addLineSafe(lines_with_constant, "dichas criaturas...", "ENDING_LINE11", 17);
        addLineSafe(lines_with_constant, "Espero de verdad no tener que", "ENDING_LINE12", 17);
        addLineSafe(lines_with_constant, "regresar nunca a esta casa...", "ENDING_LINE13", 17);
        addLineSafe(lines_with_constant, "Profesor Edward Kelvin", "ENDING_LINE14", 17);

        addLineSafe(lines_with_constant, "Gracias por jugar a", "ENDING2_LINE1", 17);
        addLineSafe(lines_with_constant, "Westen House ex", "ENDING2_LINE2", 17);
        addLineSafe(lines_with_constant, "Brain Games, 2022", "ENDING2_LINE3", 17);
        addLineSafe(lines_with_constant, "santi.ontanon@gmail.com", "ENDING2_LINE4", 17);
        addLineSafe(lines_with_constant, "Código/Gráficos:", "ENDING2_LINE5", 17);
        addLineSafe(lines_with_constant, "      Santiago Ontañón", "ENDING2_LINE6", 17);
        addLineSafe(lines_with_constant, "Música/SFX:", "ENDING2_LINE7", 17);
        addLineSafe(lines_with_constant, "      Gryzor87", "ENDING2_LINE8", 17);
        addLineSafe(lines_with_constant, "Portada:", "ENDING2_LINE9", 17);
        addLineSafe(lines_with_constant, "      Sirelion", "ENDING2_LINE10", 17);
        addLineSafe(lines_with_constant, "Beta testeo:", "ENDING2_LINE11", 17);
        addLineSafe(lines_with_constant, "      Jordi Sureda, Araubi", "ENDING2_LINE12", 17);
        addLineSafe(lines_with_constant, "      Manuel Pazos", "ENDING2_LINE13", 17);
        addLineSafe(lines_with_constant, "Gracias a WYZ, este juego", "ENDING2_LINE14", 17);
        addLineSafe(lines_with_constant, "usa wyztracker (tm)", "ENDING2_LINE15", 17);
        
        // EX sentences:
        if (ex) {
            addLineSafe(lines_with_constant, "¡Mi colección de libros de ciencia!", "USE_BOOKSHELVES", 19);
            addLineSafe(lines_with_constant, "Tengo demasiados libros...", "USE_BOOK_STACK_HOME", 19);
            addLineSafe(lines_with_constant, "Mi querida maleta.", "USE_LUGGAGE", 19);
            addLineSafe(lines_with_constant, "El diario de hoy. Luego lo leo...", "USE_NEWSPAPER", 19);
            addLineSafe(lines_with_constant, "Papeleo de la universidad ...", "USE_UNIVERSITY_NOTES", 19);

            addLineSafe(lines_with_constant, "¡Esa es la dirección equivocada!", "WRONG_WAY", 19);
            addLineSafe(lines_with_constant, "¡No quiero caminar hasta tan lejos!", "TOO_FAR", 19);

            addLineSafe(lines_with_constant, "No quiero robar eso...", "USE_BEGGAR_BAG", 19);
            addLineSafe(lines_with_constant, "¡Hola!", "HELLO", 19);
            addLineSafe(lines_with_constant, "Mendigo: ¡¡Estamos condenados!!", "USE_BEGGAR1", 19);
            addLineSafe(lines_with_constant, "¿Por qué? ¿Estás bien?", "USE_BEGGAR2", 19);
            addLineSafe(lines_with_constant, "Mendigo: ¡¡No está muerta!!", "USE_BEGGAR3", 19);
            addLineSafe(lines_with_constant, "Mendigo: ¡Y volverá a por nosotros!", "USE_BEGGAR4", 19);
            addLineSafe(lines_with_constant, "Ya no quiere hablar conmigo.", "USE_BEGGAR5", 19);
            
            addLineSafe(lines_with_constant, "Ruido: ¡¡Aaaaargh!!", "EVENT_SCREAM1", 19);
            addLineSafe(lines_with_constant, "¿Qué ha sido ese grito?", "EVENT_SCREAM2", 19);
            addLineSafe(lines_with_constant, "¡Ha venido del callejón!", "EVENT_SCREAM3", 19);

            addLineSafe(lines_with_constant, "¡Está muerto! Le habrá mordido", "USE_BEGGAR_DEAD1", 19);
            addLineSafe(lines_with_constant, "un animal, porque veo que tiene", "USE_BEGGAR_DEAD2", 19);
            addLineSafe(lines_with_constant, "marcas en el cuello...", "USE_BEGGAR_DEAD3", 19);
            addLineSafe(lines_with_constant, "Mejor me voy de aquí...", "USE_BEGGAR_DEAD4", 19);
            
            addLineSafe(lines_with_constant, "¡No hay tiempo para libros!", "USE_BOOKSTORE_BOOKS", 19);
            addLineSafe(lines_with_constant, "No sé montar a caballo.", "USE_HORSE", 19);
            addLineSafe(lines_with_constant, "¡Podría tomar este coche!", "USE_HORSECAR1", 19);
            addLineSafe(lines_with_constant, "¿Dónde está el cochero?", "USE_HORSECAR2", 19);
            
            addLineSafe(lines_with_constant, "¿Ha visto usted al cochero?", "USE_CLERK2", 19);
            addLineSafe(lines_with_constant, "Tendero: Oh, ¿James? Seguro que", "USE_CLERK3", 19);
            addLineSafe(lines_with_constant, "Tendero: se ha dormido. Espere...", "USE_CLERK4", 19);
            addLineSafe(lines_with_constant, "Tendero: ¡¡¡JAAAAAAMEES!!!", "USE_CLERK5", 19);
            addLineSafe(lines_with_constant, "Tendero: ¿Quiere algún libro?", "USE_CLERK6", 19);

            addLineSafe(lines_with_constant, "Quiero 'Historia de Rumanía'.", "USE_CLERK7", 19);
            addLineSafe(lines_with_constant, "Tendero: ¡Claro! ¡Gran compra!", "USE_CLERK8", 19);
            
            addLineSafe(lines_with_constant, "No quiero ninguno de estos libros.", "USE_STORE_BOOKSHELF1", 19);
            addLineSafe(lines_with_constant, "¡'Historia de Rumanía'! ¡Siempre he", "USE_STORE_BOOKSHELF2", 19);
            addLineSafe(lines_with_constant, "querido esta edición!", "USE_STORE_BOOKSHELF3", 19);
            addLineSafe(lines_with_constant, "Le preguntaré al tendero...", "USE_STORE_BOOKSHELF4", 19);

            addLineSafe(lines_with_constant, "'Historia de Rumanía'", "USE_HISTORY_OF_ROMANIA1", 19);
            addLineSafe(lines_with_constant, "No hay necesidad de leerlo ahora.", "USE_HISTORY_OF_ROMANIA2", 19);

            addLineSafe(lines_with_constant, "¡A la estación de Fenchurch!", "USE_CHOFFEUR1", 19);
            addLineSafe(lines_with_constant, "Cochero: ¡Por supuesto!", "USE_CHOFFEUR2", 19);

            addLineSafe(lines_with_constant, "Llegué a tiempo a la estación y conseguí", "TRAVEL_CUTSCENE1", 22);
            addLineSafe(lines_with_constant, "pasaje en el tren de la noche.", "TRAVEL_CUTSCENE2", 22);
            addLineSafe(lines_with_constant, "Intentaré dormir un rato para estar", "TRAVEL_CUTSCENE3A", 22);
            addLineSafe(lines_with_constant, "descansado cuando llegue a Purfleet.", "TRAVEL_CUTSCENE4A", 22);
            addLineSafe(lines_with_constant, "No tengo sueño. Aprovecharé para", "TRAVEL_CUTSCENE3B", 22);
            addLineSafe(lines_with_constant, "leer el periódico.", "TRAVEL_CUTSCENE4B", 22);
            addLineSafe(lines_with_constant, "El titular de hoy es sobre una serie de", "TRAVEL_CUTSCENE5B", 22);
            addLineSafe(lines_with_constant, "misteriosas muertes hace un tiempo.", "TRAVEL_CUTSCENE6B", 22);
            addLineSafe(lines_with_constant, "Aparentemente con relación a un noble", "TRAVEL_CUTSCENE7B", 22);
            addLineSafe(lines_with_constant, "de Rumanía llamado Conde Drácula.", "TRAVEL_CUTSCENE8B", 22);
            addLineSafe(lines_with_constant, "Tengo curiosidad por ver si el", "TRAVEL_CUTSCENE9B", 22);
            addLineSafe(lines_with_constant, "nombre Drácula aparece en el libro de", "TRAVEL_CUTSCENE10B", 22);
            addLineSafe(lines_with_constant, "historia que acabo de comprar.", "TRAVEL_CUTSCENE11B", 22);            

            addLineSafe(lines_with_constant, "¡Una página arrancada del diario de", "LUCY_TORN_NOTE1", 19);
            addLineSafe(lines_with_constant, "Lucy! Solo se lee una frase.", "LUCY_TORN_NOTE2", 19);

            addLineSafe(lines_with_constant, "Pone: recuerda, solo aquellos que", "LUCY_TORN_NOTE3", 19);
            addLineSafe(lines_with_constant, "identifiquen el centro de cada uno", "LUCY_TORN_NOTE4", 19);
            addLineSafe(lines_with_constant, "de los cuatro tríos ganarán", "LUCY_TORN_NOTE5", 19);
            addLineSafe(lines_with_constant, "acceso a nuestro santuario.", "LUCY_TORN_NOTE6", 19);

            addLineSafe(lines_with_constant, "Oh, verdadero padre...", "LUCY_CUTSCENE1", 31);
            addLineSafe(lines_with_constant, "¡¡Soy tu humilde sirvienta!!", "LUCY_CUTSCENE2", 31);
            addLineSafe(lines_with_constant, "Oí tu llamada, y aquí estoy.", "LUCY_CUTSCENE3", 31);
            addLineSafe(lines_with_constant, "¡Te traeré de vuelta!", "LUCY_CUTSCENE4", 31);
            addLineSafe(lines_with_constant, "Y, juntos, haremos que los que", "LUCY_CUTSCENE5", 31);
            addLineSafe(lines_with_constant, "osaron enfrentarse a ti paguen caro...", "LUCY_CUTSCENE6", 31);
            
            addLineSafe(lines_with_constant, "¡Esto pinta mal!", "AFTER_LUCY_CUTSCENE1", 19);
            addLineSafe(lines_with_constant, "¿Con quién hablaba Lucy?", "AFTER_LUCY_CUTSCENE2", 19);
            addLineSafe(lines_with_constant, "¿Y dónde se ha metido?", "AFTER_LUCY_CUTSCENE3", 19);

            addLineSafe(lines_with_constant, "¡Un osario! ¿Qué otros secretos", "ENTER_SUBBASEMENT1", 19);
            addLineSafe(lines_with_constant, "esconde este lugar?", "ENTER_SUBBASEMENT2", 19);

            addLineSafe(lines_with_constant, "La placa dice:", "VLAD_STATUE1", 19);
            addLineSafe(lines_with_constant, "Vlad III (1428 - 1477)", "VLAD_STATUE2", 19);   

            addLineSafe(lines_with_constant, "¡Esto es muchísimo oro!", "GOLD_PILE1", 19);
            addLineSafe(lines_with_constant, "Pero no hay tiempo para dinero...", "GOLD_PILE2", 19);
            addLineSafe(lines_with_constant, "¡Tengo una tarea más importante!", "GOLD_PILE3", 19);

            addLineSafe(lines_with_constant, "Deletrea el", "PUZZLE_BOX1", 6);
            addLineSafe(lines_with_constant, "nombre de", "PUZZLE_BOX2", 6);
            addLineSafe(lines_with_constant, "mi tierra.", "PUZZLE_BOX3", 6);

            addLineSafe(lines_with_constant, "¡Ojalá tuviese el libro de historia", "PUZZLE_BOX_MSG_A1", 19);
            addLineSafe(lines_with_constant, "de Rumanía que siempre quise!", "PUZZLE_BOX_MSG_A2", 19);

            addLineSafe(lines_with_constant, "¡Suerte que compré el libro!", "PUZZLE_BOX_MSG_B1", 19);
            addLineSafe(lines_with_constant, "¿A qué país se refiere la pista?", "PUZZLE_BOX_MSG_C1", 19);
            
            addLineSafe(lines_with_constant, "Encontré la estatua de Vlad III,", "PUZZLE_BOX_MSG_D1", 19);
            addLineSafe(lines_with_constant, "hijo de Vlad Dracul de Transilvania.", "PUZZLE_BOX_MSG_D2", 19);
            addLineSafe(lines_with_constant, "El libro llama a Transilvania", "PUZZLE_BOX_MSG_D3", 19);
            addLineSafe(lines_with_constant, "Ultra silvam, Ardeal o Erdeuelu.", "PUZZLE_BOX_MSG_D4", 19);            

            addLineSafe(lines_with_constant, "¡La caja tenía una nota!", "PUZZLE_BOX_MSG_E1", 19);
            
            addLineSafe(lines_with_constant, "Hijos míos...", "PUZZLE_BOX_MSG_NOTE1", 22);
            addLineSafe(lines_with_constant, "Si deseáis verme, recordad como", "PUZZLE_BOX_MSG_NOTE2", 22);        
            addLineSafe(lines_with_constant, "solían llamar a mi padre. Entonces", "PUZZLE_BOX_MSG_NOTE3", 22);
            addLineSafe(lines_with_constant, "escribid su reflejo...", "PUZZLE_BOX_MSG_NOTE4", 22);

            addLineSafe(lines_with_constant, "Un diario. Pero... ¡un momento!", "VLAD_DIARY_MSG1", 19);
            addLineSafe(lines_with_constant, "¡¡Este diario cubre 400 años!!", "VLAD_DIARY_MSG2", 19);

            addLineSafe(lines_with_constant, "¡Uno de los libros tiene una nota", "REVEAL_CLUE1", 19);
            addLineSafe(lines_with_constant, "con un diagrama que me suena!", "REVEAL_CLUE2", 19);

            addLineSafe(lines_with_constant, "Lo leeré luego pero algunas páginas", "VLAD_DIARY_USE1", 19);
            addLineSafe(lines_with_constant, "me llaman la atención:", "VLAD_DIARY_USE2", 19);

            addLineSafe(lines_with_constant, "6 de junio de 1456: El todopoderoso me ha", "VLAD_DIARY1", 24);
            addLineSafe(lines_with_constant, "fallado. Desde hoy, juro luchar contra Dios", "VLAD_DIARY2", 24);
            addLineSafe(lines_with_constant, "con todo el poder de la oscuridad, hasta que", "VLAD_DIARY3", 24);
            addLineSafe(lines_with_constant, "el alma de Elisabeta sea aceptada en el cielo.", "VLAD_DIARY4", 24);

            addLineSafe(lines_with_constant, "7 de julio de 1456: Noto el poder de la", "VLAD_DIARY5", 24);
            addLineSafe(lines_with_constant, "oscuridad crecer. Pero ese maldito dios", "VLAD_DIARY6", 24);
            addLineSafe(lines_with_constant, "me ha expulsado de la luz del día...", "VLAD_DIARY7", 24);
            addLineSafe(lines_with_constant, "Todo sea por Elisabeta... ¡me vengaré!", "VLAD_DIARY8", 24);

            addLineSafe(lines_with_constant, "10 de enero de 1663: Libraré la siguiente", "VLAD_DIARY9", 24);
            addLineSafe(lines_with_constant, "batalla en la remota tierra de Inglaterra.", "VLAD_DIARY10", 24);
            addLineSafe(lines_with_constant, "Pronto trasladaré mi morada al este de su", "VLAD_DIARY11", 24);
            addLineSafe(lines_with_constant, "capital, Londres.", "VLAD_DIARY12", 24);

            addLineSafe(lines_with_constant, "2 de septiembre de 1666: Mi trabajo en", "VLAD_DIARY13", 24);
            addLineSafe(lines_with_constant, "Inglaterra está hecho. Prenderé la ciudad en", "VLAD_DIARY14", 24);
            addLineSafe(lines_with_constant, "llamas como último acto, y volveré a mi", "VLAD_DIARY15", 24);
            addLineSafe(lines_with_constant, "querida tierra natal a continuar mi plan.", "VLAD_DIARY16", 24);

            addLineSafe(lines_with_constant, "5 de diciembre de 1891: Se me requiere de", "VLAD_DIARY17", 24);
            addLineSafe(lines_with_constant, "nuevo en Inglaterra. Parece ser que la", "VLAD_DIARY18", 24);
            addLineSafe(lines_with_constant, "famila Westenra construyó su nueva casa", "VLAD_DIARY19", 24);
            addLineSafe(lines_with_constant, "sobre mi antigua morada. Tendré que ir a", "VLAD_DIARY20", 24);
            addLineSafe(lines_with_constant, "tomar posesión de su casa...", "VLAD_DIARY21", 24);
            
            addLineSafe(lines_with_constant, "Entonces, ¡a quien Lucy intenta", "VLAD_DIARY_USE3", 19);
            addLineSafe(lines_with_constant, "resucitar es Vlad Tepes!", "VLAD_DIARY_USE4", 19);
            addLineSafe(lines_with_constant, "Según el diario, fue una persona", "VLAD_DIARY_USE5", 19);
            addLineSafe(lines_with_constant, "terrible. ¡Tengo que detenerla!", "VLAD_DIARY_USE6", 19);

            addLineSafe(lines_with_constant, "Un espejo con pinta de frágil.", "USE_MIRROR", 19);
            addLineSafe(lines_with_constant, "¡He roto el espejo con el martillo!", "USE_MIRROR2", 19);
            addLineSafe(lines_with_constant, "¡El espejo cubría una cavidad", "USE_MIRROR3", 19);
            addLineSafe(lines_with_constant, "con un objeto dentro!", "USE_MIRROR4", 19);
            addLineSafe(lines_with_constant, "pero está vacía...!", "USE_MIRROR5", 19);
            addLineSafe(lines_with_constant, "Había una nota aquí que decía:", "MIRROR_CLUE1", 19);
            addLineSafe(lines_with_constant, "Lucy, he escondido las llaves en el", "MIRROR_CLUE2", 19);
            addLineSafe(lines_with_constant, "objeto que no funciona contigo.", "MIRROR_CLUE3", 19);

            addLineSafe(lines_with_constant, "¡El nuevo patrón ha funcionado!", "PENTAGRAM_REVEAL1", 19);

            addLineSafe(lines_with_constant, "El baúl rebosa cubiertos de plata.", "CHEST_CUTLERY1", 19);
            addLineSafe(lines_with_constant, "Cogeré un par.", "CHEST_CUTLERY2", 19);
            addLineSafe(lines_with_constant, "Ya he cogido cubiertos.", "CHEST_CUTLERY3", 19);
            addLineSafe(lines_with_constant, "Cubiertos de plata.", "USE_CUTLERY", 19);

            addLineSafe(lines_with_constant, "Oh, ¡espíritus de la oscuridad!", "VLAD_RITUAL_CUTSCENE1", 31);
            addLineSafe(lines_with_constant, "¡Vuestra sirvienta requiere de vuestros poderes!", "VLAD_RITUAL_CUTSCENE2", 31);
            addLineSafe(lines_with_constant, "¡Reunid de nuevo este cuerpo con su alma!", "VLAD_RITUAL_CUTSCENE3", 31);

            addLineSafe(lines_with_constant, "¡Lucy ha empezado el ritual!", "VLAD_RITUAL_MSG1", 19);
            addLineSafe(lines_with_constant, "Debo apresurarme, ¡pero no puedo", "VLAD_RITUAL_MSG2", 19);
            addLineSafe(lines_with_constant, "entrar por aquí! ¡Me vería!", "VLAD_RITUAL_MSG3", 19);

            addLineSafe(lines_with_constant, "Un caldero de hierro.", "USE_CAULDRON", 19);
            addLineSafe(lines_with_constant, "Había una pala dentro.", "TAKE_SHOVEL", 19);
            addLineSafe(lines_with_constant, "El baúl está vacío.", "TAKE_SHOVEL2", 19);
            addLineSafe(lines_with_constant, "Una pala de hierro.", "USE_SHOVEL", 19);
            addLineSafe(lines_with_constant, "¿Cómo? ¡¡Esa estatua se mueve!!", "MINI_BOSS_MSG1", 19);

            addLineSafe(lines_with_constant, "¡¡Un humano!!", "ENDING_VIGNETTE1_1",16);
            addLineSafe(lines_with_constant, "¿Cómo ha llegado hasta aquí?", "ENDING_VIGNETTE1_2",16);

            addLineSafe(lines_with_constant, "¡Nunca lo sabrás!", "ENDING_VIGNETTE2_1", 16);
            addLineSafe(lines_with_constant, "¡¡Muere criatura infame!!", "ENDING_VIGNETTE2_2", 16);

            addLineSafe(lines_with_constant, "¡Oigo a Lucy tras esa puerta!", "FINAL_PASSAGE1", 19);
            addLineSafe(lines_with_constant, "¡La podré sorprender por aquí!", "FINAL_PASSAGE2", 19);
            addLineSafe(lines_with_constant, "¡Necesito preparar una estaca!", "FINAL_PASSAGE3", 19);

            addLineSafe(lines_with_constant, "¡Por fin!", "ENDING_VIGNETTE3_1", 16);
            addLineSafe(lines_with_constant, "¡Lucy ha muerto!", "ENDING_VIGNETTE3_2", 16);

            addLineSafe(lines_with_constant, "No puedo creer que haga esto...", "OPEN_GRAVE1", 19);
            addLineSafe(lines_with_constant, "Pero debo asegurarme que Quincey", "OPEN_GRAVE2", 19);
            addLineSafe(lines_with_constant, "esté muerto y no sea otro vampiro", "OPEN_GRAVE3", 19);
            addLineSafe(lines_with_constant, "Claramente está muerto...", "OPEN_GRAVE4", 19);

            addLineSafe(lines_with_constant, "La arcilla podría serme útil.", "CLAY_INTERACT1", 19);
            addLineSafe(lines_with_constant, "Debería cogerla.", "CLAY_INTERACT2", 19);
            addLineSafe(lines_with_constant, "Un poco de arcilla.", "CLAY", 19);
            addLineSafe(lines_with_constant, "Encontré esta llave en Quincey.", "QUINCEY_KEY", 19);
            
            addLineSafe(lines_with_constant, "¡Había una llave y una nota dentro!", "QUINCEY_CHEST", 19);

            addLineSafe(lines_with_constant, "Si alguien encuentra esto, le ruego que ", "QUINCEY_LETTER1", 24);
            addLineSafe(lines_with_constant, "complete la tarea que no completé... la", "QUINCEY_LETTER2", 24);
            addLineSafe(lines_with_constant, "mansión de los Westenra esconde una", "QUINCEY_LETTER3", 24);
            addLineSafe(lines_with_constant, "abominación en el sótano. ¡Esta criatura", "QUINCEY_LETTER4", 24);
            addLineSafe(lines_with_constant, "debe ser enviada al infierno!", "QUINCEY_LETTER5", 24);
            addLineSafe(lines_with_constant, "Esta es la llave de su celda. Sed", "QUINCEY_LETTER6", 24);
            addLineSafe(lines_with_constant, "precavidos, ya que dicha criatura solo", "QUINCEY_LETTER7", 24);
            addLineSafe(lines_with_constant, "puede ser derrotada con balas de plata.", "QUINCEY_LETTER8", 24);
            addLineSafe(lines_with_constant, "Por favor acabad mi tarea...", "QUINCEY_LETTER9", 24);
            addLineSafe(lines_with_constant, "Quincey Morris", "QUINCEY_LETTER10", 24);
            
            addLineSafe(lines_with_constant, "¡Podría hacer balas de plata", "MELT_CUTLERY1", 19);
            addLineSafe(lines_with_constant, "fundiendo esto en el caldero!", "MELT_CUTLERY2", 19);

            addLineSafe(lines_with_constant, "Podría hacer un molde de bala", "CLAY_WET1", 19);
            addLineSafe(lines_with_constant, "con esto, pero está muy seco.", "CLAY_WET2", 19);
            addLineSafe(lines_with_constant, "Podría mojar la arcilla aquí, pero", "CLAY_WET3", 19);
            addLineSafe(lines_with_constant, "necesito una bala para el molde.", "CLAY_WET4", 19);

            addLineSafe(lines_with_constant, "He mojado la arcilla y he hecho un", "CLAY_WET5", 19);
            addLineSafe(lines_with_constant, "molde con una de las balas. Ahora", "CLAY_WET6", 19);
            addLineSafe(lines_with_constant, "tengo que cocer la arcilla.", "CLAY_WET7", 19);
            addLineSafe(lines_with_constant, "Un molde húmedo de bala.", "WET_MOLD", 19);

            addLineSafe(lines_with_constant, "He cocido la arcilla en la chimenea.", "MOLD_COOK1", 19);
            addLineSafe(lines_with_constant, "¡Ahora solo necesito plata fundida!", "MOLD_COOK2", 19);
            addLineSafe(lines_with_constant, "Un molde de bala.", "MOLD", 19);
            
            addLineSafe(lines_with_constant, "Podría fundir la plata, pero no", "MELT_SILVER1", 19);
            addLineSafe(lines_with_constant, "tengo un molde para hacer balas.", "MELT_SILVER2", 19);

            addLineSafe(lines_with_constant, "¡He hecho balas de plata fundiendo", "MELT_SILVER3", 19);
            addLineSafe(lines_with_constant, "plata en el molde!", "MELT_SILVER4", 19);

            addLineSafe(lines_with_constant, "Balas de plata.", "SILVER_BULLETS", 19);

            addLineSafe(lines_with_constant, "¡Esta debe ser la criatura que", "FRANKY1", 19);
            addLineSafe(lines_with_constant, "Quincey describió!", "FRANKY2", 19);
            addLineSafe(lines_with_constant, "¡Parece que no le hago daño!", "FRANKY3", 19);
            addLineSafe(lines_with_constant, "Quincey puede descansar ahora.", "FRANKY4", 19);
            addLineSafe(lines_with_constant, "He completado su tarea...", "FRANKY5", 19);
            addLineSafe(lines_with_constant, "Te quiero, padre", "FRANKY_LETTER1", 19);            

            addLineSafe(lines_with_constant, "Vampiros muertos:", "VAMPIRES_KILLED", 16);
            addLineSafe(lines_with_constant, "Progreso en misión secreta:", "SECONDARY_PROGRESS", 16);
            
            addLineSafe(lines_with_constant, "Un libro de visitas, escribiré algo.", "LOG_BOOK1", 19);
            addLineSafe(lines_with_constant, "- PARTIDA GUARDADA -", "LOG_BOOK2", 19);
            addLineSafe(lines_with_constant, "¿Continuar la partida guardada?", "CONTINUE1", 19);
            addLineSafe(lines_with_constant, "Sí", "CONTINUE2", 19);
            addLineSafe(lines_with_constant, "No", "CONTINUE3", 19);
        } else {
            // Sentences in the original, not in EX:
            addLineSafe(lines_with_constant, "¡Esta debe ser Lucy!", "ENTER_VAMPIRE3_ROOM1", 19);
            addLineSafe(lines_with_constant, "¡Lo conseguí! ¡Lucy está muerta!", "ENTER_VAMPIRE3_ROOM2", 19);
        }
        
        // Generate text spreadsheet:
        {
            List<String> allConstants = new ArrayList<>();
            HashMap<String,String> constantToLine = new HashMap<>();
            for(String line:lines_with_constant.keySet()) {
                allConstants.add(lines_with_constant.get(line));
                constantToLine.put(lines_with_constant.get(line), line);
            }
            Collections.sort(allConstants);
            for(String constant:allConstants) {
                System.out.println(constant + "\t" + constantToLine.get(constant));
            }
        }        
        
        List<Integer> capitals = font.convertStringToAssembler("ABCDEFGHIJKLMNOPQRSTUVWXYZ ");
        System.out.println("Capitals: " + capitals);
        List<Integer> puzzleMessage = font.convertStringToAssembler("VladalIIIleaTepes");
        System.out.println("puzzleMessage: " + puzzleMessage);
                
        
        for(String s:lines_with_constant.keySet()) {
            if (!lines.contains(s)) lines.add(s);
        }


        // List<String> newlines = lines;
        int textBankSize = 640;
//        List<String> newlines = optimizeGrouppings(lines, font, 512, 8000);
        List<String> newlines = Text.optimizeGrouppings(lines, font, textBankSize, 7800);
        // List<String> newlines = optimizeGrouppings(lines, font, 600);
        // List<String> newlines = optimizeGrouppings(lines, font, 640);
        // List<String> newlines = optimizeGrouppings(lines, font, 700);
//         List<String> newlines = optimizeGrouppings(lines, font, 4096);
        
        HashMap<String, Pair<Integer, Integer>> ids = new HashMap<>();
        Pair<List<Integer>,List<Integer>> sizes = EncodeText.encodeTextInBanks(newlines, font, textBankSize, "src/autogenerated", "textBank-es", ids, "zx0");
        int size_before = 0;
        int size_after = 0;
        for(Integer size:sizes.m_a) size_before += size;
        for(Integer size:sizes.m_b) size_after += size;
        System.out.println("Total size before: " + size_before);
        System.out.println("Total size after: " + size_after);
        // String constants:
        {
            FileWriter fw = new FileWriter(new File("src/autogenerated/text-constants-es.asm"));
            for(String s:lines_with_constant.keySet()) {
                fw.write("TEXT_"+lines_with_constant.get(s)+"_BANK:   equ " + ids.get(s).m_a + "\n");
                fw.write("TEXT_"+lines_with_constant.get(s)+"_IDX:   equ " + ids.get(s).m_b + "\n");            
            }
            fw.flush();
            fw.close();
        }
    }
    
    
    public static void addLineSafe(HashMap<String,String> lines_with_constant, String line, String tag, int maxWidthInTiles) throws Exception
    {
        if (font.stringWidth(line) > maxWidthInTiles*8) {
            throw new Exception("'"+line+"' is wider than " + maxWidthInTiles + " tiles! (" + font.stringWidth(line) + " pixels, vs " + maxWidthInTiles*8 + ")");
        }
        lines_with_constant.put(line, tag);
    }
}
