/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package westen;

import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Random;
import text.EncodeText;
import text.PAKFont;
import util.Pair;

/**
 *
 * @author santi
 */
public class Text {
    public static PAKFont font = null;
            
    public static void main(String args[]) throws Exception
    {
        generateTextData(false);
    }


    public static void generateTextData(boolean ex) throws Exception
    {
        if (ex) {
            font = TextES.setESFont();
            font.generateAssemblerData("src/autogenerated/font-es");
        } else {
            List<String> characters = new ArrayList<>();
            characters.add(" !/@'()?,-.");
            characters.add("0123456789:");
            characters.add("ABCDEFGHIJKLMNO");
            characters.add("PQRSTUVWXYZ");
            characters.add("abcdefghijklmno");
            characters.add("pqrstuvwxyzó");
            characters.add("ñ");
            font = new PAKFont("data/font.png", characters);
            font.generateAssemblerData("src/autogenerated/font");
        }
        
        font.printFontInfo();
                
        // Text lines:
        List<String> lines = new ArrayList<>();
        
        HashMap<String,String> lines_with_constant = new HashMap<>();
        addLineSafe(lines_with_constant, "Presents", "PRESENTS", 8);

        addLineSafe(lines_with_constant, "London, 1898", "INTRO_MSG1", 8);
        addLineSafe(lines_with_constant, "Ding Dong!", "INTRO_MSG2", 8);
        addLineSafe(lines_with_constant, "Coming!", "INTRO_MSG3", 8);
        addLineSafe(lines_with_constant, "A letter for you, Professor.", "INTRO_MSG4", 16);
        addLineSafe(lines_with_constant, "Thank you, Richard!", "INTRO_MSG5", 12);
        addLineSafe(lines_with_constant, "Let's see what it says...", "INTRO_MSG6", 16);
        addLineSafe(lines_with_constant, "Terrible news!", "INTRO_MSG7", 12);
        addLineSafe(lines_with_constant, "JW was a dear friend!", "INTRO_MSG8", 12);
        addLineSafe(lines_with_constant, "I must go there at once!", "INTRO_MSG9", 14);
        
        addLineSafe(lines_with_constant, "Dear Professor Edward Kelvin","LETTER1_LINE1", 28);
        addLineSafe(lines_with_constant, "We regret to inform you of the passing of Jonathan","LETTER1_LINE2", 28);
        addLineSafe(lines_with_constant, "Westen, who died on October 16th. In his will, Mr.","LETTER1_LINE3", 28);
        addLineSafe(lines_with_constant, "Westen left you his scientific notes. He also","LETTER1_LINE4", 28);
        addLineSafe(lines_with_constant, "wrote a letter for you, which we've enclosed here.","LETTER1_LINE5", 28);
        addLineSafe(lines_with_constant, "We also inform you that Mrs. Lucy Westen plans","LETTER1_LINE6", 28);
        addLineSafe(lines_with_constant, "to take possession of the house on December 1st.","LETTER1_LINE7", 28);

        if (ex) {
            addLineSafe(lines_with_constant, "If you are reading this, I am probably","LETTER2_LINE2", 24);
            addLineSafe(lines_with_constant, "dead. You must retrieve my scientific","LETTER2_LINE3", 24);
            addLineSafe(lines_with_constant, "notes before my sister Lucy takes","LETTER2_LINE4", 24);
            addLineSafe(lines_with_constant, "possession of our house in Purfleet. Only","LETTER2_LINE5", 24);
            addLineSafe(lines_with_constant, "you will understand them! Here is the key to","LETTER2_LINE6", 24);
            addLineSafe(lines_with_constant, "Westen House, and part of a key that you","LETTER2_LINE7", 24);
            addLineSafe(lines_with_constant, "will need to reach my laboratory. It is","LETTER2_LINE8", 24);
            addLineSafe(lines_with_constant, "important to me.","LETTER2_LINE9", 24);
        } else {
            addLineSafe(lines_with_constant, "If you are reading this, I am probably","LETTER2_LINE2", 24);
            addLineSafe(lines_with_constant, "dead. You must retrieve my scientific","LETTER2_LINE3", 24);
            addLineSafe(lines_with_constant, "notes before my sister Lucy takes","LETTER2_LINE4", 24);
            addLineSafe(lines_with_constant, "possession of the house. Only you will be","LETTER2_LINE5", 24);
            addLineSafe(lines_with_constant, "able to understand them! Here is the key to","LETTER2_LINE6", 24);
            addLineSafe(lines_with_constant, "Westen House, and part of a key that you","LETTER2_LINE7", 24);
            addLineSafe(lines_with_constant, "will need to reach my laboratory. It is","LETTER2_LINE8", 24);
            addLineSafe(lines_with_constant, "important to me.","LETTER2_LINE9", 24);            
        }
        
        addLineSafe(lines_with_constant, "Safe: 15-30-10", "LETTER3_LINE1_SECRET", 9);
        addLineSafe(lines_with_constant, "Dear Ed,", "LETTER3_LINE1", 22);
        addLineSafe(lines_with_constant, "I hope you find this before my family", "LETTER3_LINE2", 22);
        addLineSafe(lines_with_constant, "does. It holds the secret to the second", "LETTER3_LINE3", 22);
        addLineSafe(lines_with_constant, "half of the key you should already have.", "LETTER3_LINE4", 22);
        addLineSafe(lines_with_constant, "I used lemon ink. You will know what to do.", "LETTER3_LINE5", 22);
        addLineSafe(lines_with_constant, "You'll soon understand the secrecy.", "LETTER3_LINE6", 22);
        addLineSafe(lines_with_constant, "JW", "LETTER3_LINE7", 22);
        
        addLineSafe(lines_with_constant, "Now that you have seen the house firsthand", "LETTER4_LINE2", 24);
        addLineSafe(lines_with_constant, "you might have already guessed. My family's", "LETTER4_LINE3", 24);
        addLineSafe(lines_with_constant, "name is not Westen, but Westenra.", "LETTER4_LINE4", 24);
        addLineSafe(lines_with_constant, "We hid our name to hide my sister's identity.", "LETTER4_LINE5", 24);
        addLineSafe(lines_with_constant, "As you might recall, Lucy Westenra was in-", "LETTER4_LINE6", 24);
        addLineSafe(lines_with_constant, "volved in an unfortunate accident two years", "LETTER4_LINE7", 24);
        addLineSafe(lines_with_constant, "ago in an encounter with a creature they call", "LETTER4_LINE8", 24);
        addLineSafe(lines_with_constant, "a vampire. They are all vampires now, Ed!", "LETTER4_LINE9", 24);
        addLineSafe(lines_with_constant, "She did not die as the news said, and she", "LETTER4_LINE10", 24);
        addLineSafe(lines_with_constant, "is not alone. But I have a plan. I know how", "LETTER4_LINE11", 24);
        addLineSafe(lines_with_constant, "to kill them. Seek their coffins, they sleep", "LETTER4_LINE12", 24);
        addLineSafe(lines_with_constant, "there. Rub them with garlic before they", "LETTER4_LINE13", 24);
        addLineSafe(lines_with_constant, "arrive, and they will perish in their sleep!", "LETTER4_LINE14", 24);
        addLineSafe(lines_with_constant, "Work quickly! Prepare it before they arrive!", "LETTER4_LINE15", 24);
        addLineSafe(lines_with_constant, "If you are too late, killing them will be hard!", "LETTER4_LINE16", 24);
        addLineSafe(lines_with_constant, "You will need to drive a stake rubbed", "LETTER4_LINE17", 24);
        addLineSafe(lines_with_constant, "in garlic into their hearts while they sleep.", "LETTER4_LINE18", 24);
        addLineSafe(lines_with_constant, "I hope you do not need to resort to this!", "LETTER4_LINE19", 24);
        addLineSafe(lines_with_constant, "Best of luck! JW", "LETTER4_LINE20", 24);
        
        addLineSafe(lines_with_constant, "P.S.:", "LETTER5_LINE0", 24);
        addLineSafe(lines_with_constant, "Vampires in my family sleep in coffins in", "LETTER5_LINE1", 24);
        addLineSafe(lines_with_constant, "the basement of the house. I noticed they", "LETTER5_LINE2", 24);
        addLineSafe(lines_with_constant, "locked their doors with a combination lock.", "LETTER5_LINE3", 24);
        addLineSafe(lines_with_constant, "I think they used their vampire names as", "LETTER5_LINE4", 24);
        addLineSafe(lines_with_constant, "the pass words. Vampires keep their names", "LETTER5_LINE5", 24);
        addLineSafe(lines_with_constant, "secretively, but probably you can find them", "LETTER5_LINE6", 24);
        addLineSafe(lines_with_constant, "by searching their rooms for diaries or", "LETTER5_LINE7", 24);
        addLineSafe(lines_with_constant, "other notes.", "LETTER5_LINE8", 24);

        addLineSafe(lines_with_constant, "John Seward's Diary.", "DIARY1_LINE1", 24);
        addLineSafe(lines_with_constant, "...", "DIARY1_LINE2", 24);
        addLineSafe(lines_with_constant, "July 7th, 1897", "DIARY1_LINE3", 24);
        addLineSafe(lines_with_constant, "Mrs. Lucy finally made me part of her inner", "DIARY1_LINE4", 24);
        addLineSafe(lines_with_constant, "circle! I will now use the name of this month", "DIARY1_LINE5", 24);
        addLineSafe(lines_with_constant, "as my own to remember this occasion!", "DIARY1_LINE6", 24);

        addLineSafe(lines_with_constant, "Arthur Holmwood's Diary.", "DIARY2_LINE1", 24);
        addLineSafe(lines_with_constant, "June 26th, 1897", "DIARY2_LINE3", 24);
        addLineSafe(lines_with_constant, "My beloved finally converted me. This is", "DIARY2_LINE4", 24);
        addLineSafe(lines_with_constant, "exhilarating. I need to choose a name now.", "DIARY2_LINE5", 24);
        addLineSafe(lines_with_constant, "I think I will pick her family name to", "DIARY2_LINE6", 24);
        addLineSafe(lines_with_constant, "show my devotion.", "DIARY2_LINE7", 24);
        
        addLineSafe(lines_with_constant, "Press SPACE to Start", "START", 16);
        addLineSafe(lines_with_constant, "Press M for controls", "CONTROLS", 16);
        
        addLineSafe(lines_with_constant, "Game Over", "GAME_OVER", 8);

        addLineSafe(lines_with_constant, "Joystick / arrow keys to move.", "TUTORIAL1_LINE1", 17);
        addLineSafe(lines_with_constant, "Button 1 / space to jump.", "TUTORIAL1_LINE2", 17);
        addLineSafe(lines_with_constant, "Q to toggle direction mapping.", "TUTORIAL1_LINE3", 17);

        addLineSafe(lines_with_constant, "While holding Button 2 / M:", "TUTORIAL2_LINE1", 18);
        addLineSafe(lines_with_constant, "- Joystick / arrow keys to", "TUTORIAL2_LINE2", 18);
        addLineSafe(lines_with_constant, "  select inventory items,", "TUTORIAL2_LINE3", 18);
        addLineSafe(lines_with_constant, "- Button 1 / space to use them.", "TUTORIAL2_LINE4", 18);
        
        addLineSafe(lines_with_constant, "Some objects can be pushed by", "TUTORIAL3_LINE1", 17);
        addLineSafe(lines_with_constant, "walking into them.", "TUTORIAL3_LINE2", 17);

        addLineSafe(lines_with_constant, "To interact with a room object: get", "TUTORIAL4_LINE1", 20);
        addLineSafe(lines_with_constant, "close by with an empty inventory slot", "TUTORIAL4_LINE2", 20);
        addLineSafe(lines_with_constant, "selected, and press Button 1 / space", "TUTORIAL4_LINE3", 20);
        addLineSafe(lines_with_constant, "while holding Button 2 / M.", "TUTORIAL4_LINE4", 20);
        addLineSafe(lines_with_constant, "To pick it up: do the same while", "TUTORIAL4_LINE5", 20);
        addLineSafe(lines_with_constant, "standing on top of the object.", "TUTORIAL4_LINE6", 20);

        if (ex) {
            addLineSafe(lines_with_constant, "Brain Games (2022)", "CREDITS1", 24);
            addLineSafe(lines_with_constant, "Code/Graphics: Santiago Ontañón", "CREDITS2", 24);
            addLineSafe(lines_with_constant, "Music/SFX: Gryzor87    Cover Art: Sirelion", "CREDITS3", 24);

            addLineSafe(lines_with_constant, "I can make it to the train station", "GAME_START_MESSSAGE1", 19);
            addLineSafe(lines_with_constant, "tonight if I hurry! I just need", "GAME_START_MESSSAGE2", 19);        
            addLineSafe(lines_with_constant, "to get my luggage!", "GAME_START_MESSSAGE3", 19);        

            addLineSafe(lines_with_constant, "I need my luggage first!", "NEED_LUGGAGE", 19);        

            addLineSafe(lines_with_constant, "I just arrived at Westen House.", "HOUSE_ARRIVAL_MESSSAGE1", 19);
            addLineSafe(lines_with_constant, "Let's find JW's laboratory.", "HOUSE_ARRIVAL_MESSSAGE2", 19);        
        } else {
            addLineSafe(lines_with_constant, "Santiago Ontañón 2021", "CREDITS", 16);

            addLineSafe(lines_with_constant, "I just arrived at Westen House.", "GAME_START_MESSSAGE1", 19);
            addLineSafe(lines_with_constant, "Let's find JW's laboratory.", "GAME_START_MESSSAGE2", 19);                        
        }

        addLineSafe(lines_with_constant, "I'll leave the stools behind.", "DROP_STOOLS", 19);
        addLineSafe(lines_with_constant, "A note from JW! Let's read it!", "LETTER3", 19);

        addLineSafe(lines_with_constant, "Nothing here to use or pick up.", "USE_ERROR", 19);
        addLineSafe(lines_with_constant, "I don't see the appropriate lock.", "ITEM_KEY", 19);
        addLineSafe(lines_with_constant, "Looks like the key for a chest.", "ITEM_KEY_GUN", 19);
        addLineSafe(lines_with_constant, "I need to find the other half.", "ITEM_HALF_KEY", 19);
        addLineSafe(lines_with_constant, "A bottle of lamp oil.", "ITEM_OIL", 19);
        addLineSafe(lines_with_constant, "I'll refill the lamp with this oil.", "ITEM_OIL_USED", 19);
        addLineSafe(lines_with_constant, "An oil lamp. It's out of oil.", "ITEM_LAMP", 19);
        addLineSafe(lines_with_constant, "An oil lamp. The flame is on.", "ITEM_LAMP_ON", 19);
        addLineSafe(lines_with_constant, "The lamp heat is developing", "USE_LAMP1", 19);
        addLineSafe(lines_with_constant, "the lemon ink in the letter!", "USE_LAMP2", 19);
        addLineSafe(lines_with_constant, "There is nothing behind this painting.", "USE_PAINTING", 19);
        addLineSafe(lines_with_constant, "Look! A safe behind this painting!", "USE_PAINTING_SAFE", 19);
        addLineSafe(lines_with_constant, "I don't know the combination.", "USE_SAFE", 19);
        addLineSafe(lines_with_constant, "Aha! The letter code worked!", "USE_SAFE_OPEN1", 19);
        addLineSafe(lines_with_constant, "There is nothing else inside.", "USE_SAFE_OPEN2", 19);
        addLineSafe(lines_with_constant, "The two halves fit perfectly!", "MERGE_RED_KEY", 19);
        addLineSafe(lines_with_constant, "There is a loose page.", "USE_BOOK", 19);
        addLineSafe(lines_with_constant, "I don't want to put the candle here.", "USE_CANDLE", 19);
        
        addLineSafe(lines_with_constant, "Quincey Morris, 1862 - 1897", "USE_TOMBSTONE", 19);
        addLineSafe(lines_with_constant, "This door is locked.", "USE_DOOR", 19);
        addLineSafe(lines_with_constant, "Lots of dark arts books.", "USE_BOOK_STACK", 19);
        addLineSafe(lines_with_constant, "This chest is just decorative.", "USE_CHEST", 19);
        addLineSafe(lines_with_constant, "I don't feel like going now.", "USE_TOILET", 19);
        addLineSafe(lines_with_constant, "No time for a bath now.", "USE_BATHTUB", 19);
        addLineSafe(lines_with_constant, "A very nice gramophone.", "USE_GRAMOPHONE", 19);
        addLineSafe(lines_with_constant, "A violin, I can't play it.", "USE_VIOLIN", 19);
        addLineSafe(lines_with_constant, "No need to wash my hands now.", "USE_SINK", 19);
        addLineSafe(lines_with_constant, "This window doesn't open.", "USE_WINDOW", 19);
        addLineSafe(lines_with_constant, "A very expensive-looking coffin.", "USE_COFFIN", 19);
        addLineSafe(lines_with_constant, "These are human remains!", "USE_BONES", 19);  
        addLineSafe(lines_with_constant, "This chest is locked.", "USE_CHEST_GUN1", 19);
        addLineSafe(lines_with_constant, "Nothing else in this chest.", "USE_CHEST_GUN2", 19);
        addLineSafe(lines_with_constant, "The key opened the chest.", "TAKE_GUN1", 19);
        addLineSafe(lines_with_constant, "There was a revolver inside!", "TAKE_GUN2", 19);
        
        addLineSafe(lines_with_constant, "An accounting book. It's strange,", "USE_BOOK_WESTENRA1", 19);
        addLineSafe(lines_with_constant, "though, since instead of Westen,", "USE_BOOK_WESTENRA2", 19);
        addLineSafe(lines_with_constant, "this is for the Westenra family...", "USE_BOOK_WESTENRA3", 19);
        
        addLineSafe(lines_with_constant, "This is the diary of Lucy Westenra.", "USE_DIARY3_1", 19);
        addLineSafe(lines_with_constant, "Most pages are torn, but I found", "USE_DIARY3_2", 19);
        addLineSafe(lines_with_constant, "a key inside.", "USE_DIARY3_3", 19);

        addLineSafe(lines_with_constant, "So, Lucy Westen is Lucy Westenra!", "USE_LAB_NOTES_1", 19);
        addLineSafe(lines_with_constant, "This is worse than I thought!", "USE_LAB_NOTES_2", 19);
        addLineSafe(lines_with_constant, "I need to hurry and find garlic!", "USE_LAB_NOTES_3", 19);

        addLineSafe(lines_with_constant, "This crate looks fairly weak...", "USE_BREAKABLE_CRATE", 19);
        addLineSafe(lines_with_constant, "Nothing I can break nearby.", "USE_HAMMER1", 19);
        addLineSafe(lines_with_constant, "I smashed it with the hammer!", "USE_HAMMER2", 19);

        addLineSafe(lines_with_constant, "A clove of garlic.", "USE_GARLIC1", 19);
        addLineSafe(lines_with_constant, "I rubbed the stake with the garlic.", "USE_GARLIC2", 19);
        addLineSafe(lines_with_constant, "A wooden stake.", "USE_STAKE", 19);
        addLineSafe(lines_with_constant, "A wooden stake rubbed in garlic.", "USE_RUBBED_STAKE", 19);
        addLineSafe(lines_with_constant, "Not now! The vampire is awake!", "USE_RUBBED_STAKE_AWAKE", 19);
        addLineSafe(lines_with_constant, "I need to get closer!", "USE_RUBBED_STAKE_TOO_FAR", 19);
        addLineSafe(lines_with_constant, "It worked! I killed it!", "USE_RUBBED_STAKE_KILL", 19);

        addLineSafe(lines_with_constant, "The door has a combination lock.", "USE_VAMPIRE_DOOR", 19);
        
        addLineSafe(lines_with_constant, "How strange, this part of the", "MSG_ABANDONED1", 19);
        addLineSafe(lines_with_constant, "house looks abandoned...", "MSG_ABANDONED2", 19);

        addLineSafe(lines_with_constant, "This room is full of books about", "MSG_BOOKS1", 19);
        addLineSafe(lines_with_constant, "the dark arts!", "MSG_BOOKS2", 19);
        addLineSafe(lines_with_constant, "Why would JW have these?!", "MSG_BOOKS3", 19);

        addLineSafe(lines_with_constant, "What is this?! Was JW conducting", "MSG_PENTAGRAM1", 19);
        addLineSafe(lines_with_constant, "unholy rituals?!", "MSG_PENTAGRAM2", 19);

        addLineSafe(lines_with_constant, "The door opened! I thought I was", "MSG_PENTAGRAM_SOLVED1", 19);
        addLineSafe(lines_with_constant, "just looking for JW's lab, but this", "MSG_PENTAGRAM_SOLVED2", 19);
        addLineSafe(lines_with_constant, "house is stranger than I thought!", "MSG_PENTAGRAM_SOLVED3", 19);
        
        addLineSafe(lines_with_constant, "Human remains!", "MSG_FEEDING1", 19);
        addLineSafe(lines_with_constant, "Ok, it is now clear that something", "MSG_FEEDING2", 19);
        addLineSafe(lines_with_constant, "macabre was going on in this house!", "MSG_FEEDING3", 19);

        addLineSafe(lines_with_constant, "At last! JW's laboratory!", "MSG_LAB", 19);

        addLineSafe(lines_with_constant, "Wait, I hear noises downstairs!", "MSG_FAMILY_CUTSCENE1", 19);
        addLineSafe(lines_with_constant, "Arthur: At last! That brother of yours is dead!", "MSG_FAMILY_CUTSCENE2", 31);
        addLineSafe(lines_with_constant, "Lucy: Indeed! The house is now mine!", "MSG_FAMILY_CUTSCENE3", 31);
        addLineSafe(lines_with_constant, "Lucy: I longed for entering my basement in peace!", "MSG_FAMILY_CUTSCENE4", 31);
        addLineSafe(lines_with_constant, "Lucy: From this house we will build our family!!", "MSG_FAMILY_CUTSCENE5", 31);
        addLineSafe(lines_with_constant, "Lucy: Today it's only us, but tomorrow we will grow!!", "MSG_FAMILY_CUTSCENE6", 31);
        addLineSafe(lines_with_constant, "Lucy: Hahaha", "MSG_FAMILY_CUTSCENE7A", 31);
        addLineSafe(lines_with_constant, "John: Hahaha", "MSG_FAMILY_CUTSCENE7B", 31);
        addLineSafe(lines_with_constant, "Arthur: Hahaha", "MSG_FAMILY_CUTSCENE7C", 31);
        addLineSafe(lines_with_constant, "Lucy: But today we rest! Let's go!", "MSG_FAMILY_CUTSCENE8", 31);

        addLineSafe(lines_with_constant, "I cannot believe my eyes!", "MSG_FAMILY_CUTSCENE9", 19);
        addLineSafe(lines_with_constant, "They are here! I was too slow!", "MSG_FAMILY_CUTSCENE10", 19);
        addLineSafe(lines_with_constant, "I will need to use the stakes...", "MSG_FAMILY_CUTSCENE11", 19);
        
        addLineSafe(lines_with_constant, "It opened!", "OPEN_VAMPIRE1_DOOR", 19);
        addLineSafe(lines_with_constant, "I don't need this diary anymore...", "OPEN_VAMPIRE1_DOOR2", 19);
        addLineSafe(lines_with_constant, "A vampire!", "ENTER_VAMPIRE_ROOM1", 19);
        addLineSafe(lines_with_constant, "I'll approach while it sleeps...", "ENTER_VAMPIRE_ROOM2", 19);
        
        addLineSafe(lines_with_constant, "I found a note in the corpse.", "FIND_VAMPIRE_NOTE", 19);
        
        addLineSafe(lines_with_constant, "John Seward's to do:", "VAMPIRE1_NOTE1", 24);
        addLineSafe(lines_with_constant, "- Kill JW (done)", "VAMPIRE1_NOTE2", 24);
        addLineSafe(lines_with_constant, "- Find my diary", "VAMPIRE1_NOTE3", 24);
        addLineSafe(lines_with_constant, "- Thank Lucy for using our initials to", "VAMPIRE1_NOTE4", 24);
        addLineSafe(lines_with_constant, "  form her vampire name. Such an honor", "VAMPIRE1_NOTE5", 24);
        addLineSafe(lines_with_constant, "  for all three of us!", "VAMPIRE1_NOTE6", 24);

        addLineSafe(lines_with_constant, "Lucy, why did you need to use the ini-", "VAMPIRE2_NOTE1", 22);
        addLineSafe(lines_with_constant, "tials from those two as well? I am your", "VAMPIRE2_NOTE2", 22);        
        addLineSafe(lines_with_constant, "husband! At least you put mine first...", "VAMPIRE2_NOTE3", 22);
        addLineSafe(lines_with_constant, "Arthur Holmwood", "VAMPIRE2_NOTE4", 22);
                        
        addLineSafe(lines_with_constant, "December 2nd, 1898", "ENDING_LINE1", 17);
        
        addLineSafe(lines_with_constant, "I still don't know how to feel", "ENDING_LINE2", 17);
        addLineSafe(lines_with_constant, "about the events that took", "ENDING_LINE3", 17);
        addLineSafe(lines_with_constant, "place in Westen... I mean", "ENDING_LINE4", 17);
        addLineSafe(lines_with_constant, "Westenra house...", "ENDING_LINE5", 17);

        addLineSafe(lines_with_constant, "Although I am relieved to have", "ENDING_LINE6", 17);
        addLineSafe(lines_with_constant, "rid the world of those beasts", "ENDING_LINE7", 17);
        addLineSafe(lines_with_constant, "and have come out alive, I am", "ENDING_LINE8", 17);
        addLineSafe(lines_with_constant, "saddened to learn that the life", "ENDING_LINE9", 17);
        addLineSafe(lines_with_constant, "of my good friend ended", "ENDING_LINE10", 17);
        addLineSafe(lines_with_constant, "because of such creatures...", "ENDING_LINE11", 17);

        addLineSafe(lines_with_constant, "I really hope I do not need to", "ENDING_LINE12", 17);
        addLineSafe(lines_with_constant, "ever return to this house...", "ENDING_LINE13", 17);

        addLineSafe(lines_with_constant, "Professor Edward Kelvin", "ENDING_LINE14", 17);

        addLineSafe(lines_with_constant, "Thank you for playing", "ENDING2_LINE1", 17);
        addLineSafe(lines_with_constant, "Westen House ex", "ENDING2_LINE2", 17);
        addLineSafe(lines_with_constant, "Brain Games, 2022", "ENDING2_LINE3", 17);
        addLineSafe(lines_with_constant, "santi.ontanon@gmail.com", "ENDING2_LINE4", 17);
        addLineSafe(lines_with_constant, "Code/Graphics:", "ENDING2_LINE5", 17);
        addLineSafe(lines_with_constant, "      Santiago Ontañón", "ENDING2_LINE6", 17);
        addLineSafe(lines_with_constant, "Music/SFX:", "ENDING2_LINE7", 17);
        addLineSafe(lines_with_constant, "      Gryzor87", "ENDING2_LINE8", 17);
        addLineSafe(lines_with_constant, "Cover Art:", "ENDING2_LINE9", 17);
        addLineSafe(lines_with_constant, "      Sirelion", "ENDING2_LINE10", 17);
        addLineSafe(lines_with_constant, "Beta testing:", "ENDING2_LINE11", 17);
        addLineSafe(lines_with_constant, "      Jordi Sureda, Araubi", "ENDING2_LINE12", 17);
        addLineSafe(lines_with_constant, "      Manuel Pazos", "ENDING2_LINE13", 17);
        addLineSafe(lines_with_constant, "Thanks to WYZ this game is", "ENDING2_LINE14", 17);
        addLineSafe(lines_with_constant, "powered by wyztracker (tm)", "ENDING2_LINE15", 17);
        
        // EX sentences:
        if (ex) {
            addLineSafe(lines_with_constant, "Ah! My science book collection!", "USE_BOOKSHELVES", 19);
            addLineSafe(lines_with_constant, "I have too many books...", "USE_BOOK_STACK_HOME", 19);
            addLineSafe(lines_with_constant, "My trusty travel bag.", "USE_LUGGAGE", 19);
            addLineSafe(lines_with_constant, "Today's paper. I'll read it later...", "USE_NEWSPAPER", 19);
            addLineSafe(lines_with_constant, "Endless university paperwork...", "USE_UNIVERSITY_NOTES", 19);

            addLineSafe(lines_with_constant, "That's the wrong way!", "WRONG_WAY", 19);
            addLineSafe(lines_with_constant, "I don't want to walk that far!", "TOO_FAR", 19);

            addLineSafe(lines_with_constant, "I don't want to steal that...", "USE_BEGGAR_BAG", 19);
            addLineSafe(lines_with_constant, "Hello!", "HELLO", 19);
            addLineSafe(lines_with_constant, "Homeless: We are all doomed!!", "USE_BEGGAR1", 19);
            addLineSafe(lines_with_constant, "Why? Are you ok?", "USE_BEGGAR2", 19);
            addLineSafe(lines_with_constant, "Homeless: She is not dead!!", "USE_BEGGAR3", 19);
            addLineSafe(lines_with_constant, "Homeless: She is comming for us!!", "USE_BEGGAR4", 19);
            addLineSafe(lines_with_constant, "He's not talking to me anymore.", "USE_BEGGAR5", 19);

            addLineSafe(lines_with_constant, "Noise: Aaaaargh!!", "EVENT_SCREAM1", 19);
            addLineSafe(lines_with_constant, "What was that scream?!", "EVENT_SCREAM2", 19);
            addLineSafe(lines_with_constant, "It came from the alley!", "EVENT_SCREAM3", 19);

            addLineSafe(lines_with_constant, "He's dead! He must have been", "USE_BEGGAR_DEAD1", 19);
            addLineSafe(lines_with_constant, "bitten by a wild animal, since I", "USE_BEGGAR_DEAD2", 19);
            addLineSafe(lines_with_constant, "see a bite mark in his neck!", "USE_BEGGAR_DEAD3", 19);
            addLineSafe(lines_with_constant, "I better get out of here...", "USE_BEGGAR_DEAD4", 19);

            addLineSafe(lines_with_constant, "No time to buy books now!", "USE_BOOKSTORE_BOOKS", 19);
            addLineSafe(lines_with_constant, "I don't know how to ride a horse.", "USE_HORSE", 19);
            addLineSafe(lines_with_constant, "I could ride this to the station!", "USE_HORSECAR1", 19);
            addLineSafe(lines_with_constant, "Where is the choffeur?", "USE_HORSECAR2", 19);

            addLineSafe(lines_with_constant, "Have you seen the car choffeur?", "USE_CLERK2", 19);
            addLineSafe(lines_with_constant, "Clerk: Oh, James? I bet he is just", "USE_CLERK3", 19);
            addLineSafe(lines_with_constant, "Clerk: sleeping in the car. Hold on...", "USE_CLERK4", 19);
            addLineSafe(lines_with_constant, "Clerk: JAAAAAAMEES!!!", "USE_CLERK5", 19);
            addLineSafe(lines_with_constant, "Clerk: Any book you want?", "USE_CLERK6", 19);

            addLineSafe(lines_with_constant, "Can I have 'History of Romania'?", "USE_CLERK7", 19);
            addLineSafe(lines_with_constant, "Clerk: Sure! Great purchase!", "USE_CLERK8", 19);

            addLineSafe(lines_with_constant, "I don't want any of these books.", "USE_STORE_BOOKSHELF1", 19);
            addLineSafe(lines_with_constant, "'History of Romania'! I've been", "USE_STORE_BOOKSHELF2", 19);
            addLineSafe(lines_with_constant, "looking for this edition for years!", "USE_STORE_BOOKSHELF3", 19);
            addLineSafe(lines_with_constant, "Let me check with the clerk first...", "USE_STORE_BOOKSHELF4", 19);

            addLineSafe(lines_with_constant, "'History of Romania'", "USE_HISTORY_OF_ROMANIA1", 19);
            addLineSafe(lines_with_constant, "No need to read it now.", "USE_HISTORY_OF_ROMANIA2", 19);

            addLineSafe(lines_with_constant, "To the Fenchurch train station!", "USE_CHOFFEUR1", 19);
            addLineSafe(lines_with_constant, "Choffeur: Sure thing sir!", "USE_CHOFFEUR2", 19);
            
            addLineSafe(lines_with_constant, "I was in time to the train station and I", "TRAVEL_CUTSCENE1", 22);
            addLineSafe(lines_with_constant, "got passage in the night train.", "TRAVEL_CUTSCENE2", 22);
            addLineSafe(lines_with_constant, "I will try to sleep a bit in the train to be", "TRAVEL_CUTSCENE3A", 22);
            addLineSafe(lines_with_constant, "rested when I arrive at Purfleet.", "TRAVEL_CUTSCENE4A", 22);
            addLineSafe(lines_with_constant, "I am not sleepy, so I will take the chance", "TRAVEL_CUTSCENE3B", 22);
            addLineSafe(lines_with_constant, "to read the newspaper.", "TRAVEL_CUTSCENE4B", 22);
            addLineSafe(lines_with_constant, "The main story in today's paper was", "TRAVEL_CUTSCENE5B", 22);
            addLineSafe(lines_with_constant, "about a series of mysterious deaths", "TRAVEL_CUTSCENE6B", 22);
            addLineSafe(lines_with_constant, "some time ago. Apparently linked to a", "TRAVEL_CUTSCENE7B", 22);
            addLineSafe(lines_with_constant, "romanian noble they call Count Dracula.", "TRAVEL_CUTSCENE8B", 22);
            addLineSafe(lines_with_constant, "Now I am curious to see if the Dracula", "TRAVEL_CUTSCENE9B", 22);
            addLineSafe(lines_with_constant, "family appears in the history of", "TRAVEL_CUTSCENE10B", 22);
            addLineSafe(lines_with_constant, "Romania book I just purchased.", "TRAVEL_CUTSCENE11B", 22);            
            
            addLineSafe(lines_with_constant, "A page torn from Lucy's diary! Only", "LUCY_TORN_NOTE1", 19);
            addLineSafe(lines_with_constant, "one sentence is readable.", "LUCY_TORN_NOTE2", 19);

            addLineSafe(lines_with_constant, "It reads: remember, only those who", "LUCY_TORN_NOTE3", 19);
            addLineSafe(lines_with_constant, "identify the middle one of each of", "LUCY_TORN_NOTE4", 19);
            addLineSafe(lines_with_constant, "the four triplets will be allowed", "LUCY_TORN_NOTE5", 19);
            addLineSafe(lines_with_constant, "into the inner sanctum.", "LUCY_TORN_NOTE6", 19);
            
            addLineSafe(lines_with_constant, "Oh, my real Father!", "LUCY_CUTSCENE1", 31);
            addLineSafe(lines_with_constant, "I am your servant!!", "LUCY_CUTSCENE2", 31);
            addLineSafe(lines_with_constant, "I heard your call, and I came.", "LUCY_CUTSCENE3", 31);
            addLineSafe(lines_with_constant, "I will bring you back!", "LUCY_CUTSCENE4", 31);
            addLineSafe(lines_with_constant, "And, together, we will make those", "LUCY_CUTSCENE5", 31);
            addLineSafe(lines_with_constant, "who dared try to stop you pay!", "LUCY_CUTSCENE6", 31);

            addLineSafe(lines_with_constant, "I don't like this!", "AFTER_LUCY_CUTSCENE1", 19);
            addLineSafe(lines_with_constant, "Who was Lucy talking to?", "AFTER_LUCY_CUTSCENE2", 19);
            addLineSafe(lines_with_constant, "And where did she go?", "AFTER_LUCY_CUTSCENE3", 19);

            addLineSafe(lines_with_constant, "An ossuary! What other secrets is", "ENTER_SUBBASEMENT1", 19);
            addLineSafe(lines_with_constant, "this house hiding?", "ENTER_SUBBASEMENT2", 19);

            addLineSafe(lines_with_constant, "The plaque says:", "VLAD_STATUE1", 19);
            addLineSafe(lines_with_constant, "Vlad III (1428 - 1477)", "VLAD_STATUE2", 19);   
            
            addLineSafe(lines_with_constant, "Wow, this is a lot of gold!", "GOLD_PILE1", 19);
            addLineSafe(lines_with_constant, "But no time for money now...", "GOLD_PILE2", 19);
            addLineSafe(lines_with_constant, "I have a more important task!", "GOLD_PILE3", 19);

            addLineSafe(lines_with_constant, "Spell the", "PUZZLE_BOX1", 6);
            addLineSafe(lines_with_constant, "first name", "PUZZLE_BOX2", 6);
            addLineSafe(lines_with_constant, "of my land.", "PUZZLE_BOX3", 6);

            addLineSafe(lines_with_constant, "I wish I got the Romanian history", "PUZZLE_BOX_MSG_A1", 19);
            addLineSafe(lines_with_constant, "book I have wanted for some time!", "PUZZLE_BOX_MSG_A2", 19);

            addLineSafe(lines_with_constant, "Glad I bought that book now!", "PUZZLE_BOX_MSG_B1", 19);
            addLineSafe(lines_with_constant, "Which land is the clue referring to?", "PUZZLE_BOX_MSG_C1", 19);

            addLineSafe(lines_with_constant, "I found the statue of Vlad III, son", "PUZZLE_BOX_MSG_D1", 19);
            addLineSafe(lines_with_constant, "of Vlad Dracul born in Transylvania.", "PUZZLE_BOX_MSG_D2", 19);
            addLineSafe(lines_with_constant, "The book also calls Transylvania", "PUZZLE_BOX_MSG_D3", 19);
            addLineSafe(lines_with_constant, "Ultra silvam, Ardeal and Erdeuelu.", "PUZZLE_BOX_MSG_D4", 19);

            addLineSafe(lines_with_constant, "The box contained a note!", "PUZZLE_BOX_MSG_E1", 19);
            
            addLineSafe(lines_with_constant, "Oh, my children...", "PUZZLE_BOX_MSG_NOTE1", 22);
            addLineSafe(lines_with_constant, "If you wish to see me, remember how", "PUZZLE_BOX_MSG_NOTE2", 22);        
            addLineSafe(lines_with_constant, "they used to call my father. Then,", "PUZZLE_BOX_MSG_NOTE3", 22);
            addLineSafe(lines_with_constant, "write its reflection...", "PUZZLE_BOX_MSG_NOTE4", 22);

            addLineSafe(lines_with_constant, "A personal diary. But wait!", "VLAD_DIARY_MSG1", 19);
            addLineSafe(lines_with_constant, "This diary covers over 400 years!", "VLAD_DIARY_MSG2", 19);

            addLineSafe(lines_with_constant, "One of the books has a note with a", "REVEAL_CLUE1", 19);
            addLineSafe(lines_with_constant, "diagram that looks familiar!", "REVEAL_CLUE2", 19);

            addLineSafe(lines_with_constant, "I will read it later, but there are", "VLAD_DIARY_USE1", 19);
            addLineSafe(lines_with_constant, "some pages that call my attention:", "VLAD_DIARY_USE2", 19);

            addLineSafe(lines_with_constant, "June 6th, 1456: The Almighty has failed me.", "VLAD_DIARY1", 24);
            addLineSafe(lines_with_constant, "From this day, I swear I will fight God with", "VLAD_DIARY2", 24);
            addLineSafe(lines_with_constant, "all the powers of darkness until the innocent", "VLAD_DIARY3", 24);
            addLineSafe(lines_with_constant, "soul of Elisabeta is accepted into Heaven.", "VLAD_DIARY4", 24);

            addLineSafe(lines_with_constant, "July 7th, 1456: As the dark power grows", "VLAD_DIARY5", 24);
            addLineSafe(lines_with_constant, "within me, that damned Almighty fights", "VLAD_DIARY6", 24);
            addLineSafe(lines_with_constant, "back and has banished me from daylight...", "VLAD_DIARY7", 24);
            addLineSafe(lines_with_constant, "But for my Elisabeta I will have revenge!", "VLAD_DIARY8", 24);

            addLineSafe(lines_with_constant, "January 10th, 1663: I decided to continue", "VLAD_DIARY9", 24);
            addLineSafe(lines_with_constant, "my battle in the remote country of England.", "VLAD_DIARY10", 24);
            addLineSafe(lines_with_constant, "I will soon move to my new lair east of their", "VLAD_DIARY11", 24);
            addLineSafe(lines_with_constant, "capital city, London.", "VLAD_DIARY12", 24);

            addLineSafe(lines_with_constant, "September 2nd, 1666: My work in England is", "VLAD_DIARY13", 24);
            addLineSafe(lines_with_constant, "over. I will set the city ablaze as my last", "VLAD_DIARY14", 24);
            addLineSafe(lines_with_constant, "act. I will move back to my homeland, where", "VLAD_DIARY15", 24);
            addLineSafe(lines_with_constant, "I will continue my revenge.", "VLAD_DIARY16", 24);

            addLineSafe(lines_with_constant, "December 5th, 1891: My presence is required", "VLAD_DIARY17", 24);
            addLineSafe(lines_with_constant, "in England once again. My old lair suffered", "VLAD_DIARY18", 24);
            addLineSafe(lines_with_constant, "damage and the Westenras built a new house", "VLAD_DIARY19", 24);
            addLineSafe(lines_with_constant, "over it. I will have to take posession of", "VLAD_DIARY20", 24);
            addLineSafe(lines_with_constant, "the Westenra house...", "VLAD_DIARY21", 24);

            addLineSafe(lines_with_constant, "So, it seems the one Lucy is trying", "VLAD_DIARY_USE3", 19);
            addLineSafe(lines_with_constant, "to resurrect is Vlad Tepes!", "VLAD_DIARY_USE4", 19);
            addLineSafe(lines_with_constant, "From the diary, he did horrible", "VLAD_DIARY_USE5", 19);
            addLineSafe(lines_with_constant, "things! I need to stop her!", "VLAD_DIARY_USE6", 19);
            
            addLineSafe(lines_with_constant, "A fragile-looking mirror.", "USE_MIRROR", 19);
            addLineSafe(lines_with_constant, "I broke the mirror with my hammer!", "USE_MIRROR2", 19);
            addLineSafe(lines_with_constant, "The mirror was covering a cavity", "USE_MIRROR3", 19);
            addLineSafe(lines_with_constant, "with an object inside!", "USE_MIRROR4", 19);
            addLineSafe(lines_with_constant, "but there was nothing inside...", "USE_MIRROR5", 19);
            addLineSafe(lines_with_constant, "There is a note here that says:", "MIRROR_CLUE1", 19);
            addLineSafe(lines_with_constant, "Lucy, I hid the keys in the object", "MIRROR_CLUE2", 19);
            addLineSafe(lines_with_constant, "that is useless to you.", "MIRROR_CLUE3", 19);

            addLineSafe(lines_with_constant, "The new pattern worked!", "PENTAGRAM_REVEAL1", 19);

            addLineSafe(lines_with_constant, "This chest is full of silver cutlery.", "CHEST_CUTLERY1", 19);
            addLineSafe(lines_with_constant, "I will take some.", "CHEST_CUTLERY2", 19);
            addLineSafe(lines_with_constant, "I have already taken some cutlery.", "CHEST_CUTLERY3", 19);
            addLineSafe(lines_with_constant, "Some silver cutlery.", "USE_CUTLERY", 19);

            addLineSafe(lines_with_constant, "Oh, spirits of the darkness!", "VLAD_RITUAL_CUTSCENE1", 31);
            addLineSafe(lines_with_constant, "I, your loyal servant, request your powers!", "VLAD_RITUAL_CUTSCENE2", 31);
            addLineSafe(lines_with_constant, "Reunite this flesh back with its soul!", "VLAD_RITUAL_CUTSCENE3", 31);
            
            addLineSafe(lines_with_constant, "Lucy has started the ritual!", "VLAD_RITUAL_MSG1", 19);
            addLineSafe(lines_with_constant, "I must hurry, but I cannot enter", "VLAD_RITUAL_MSG2", 19);
            addLineSafe(lines_with_constant, "this way! She would see me!", "VLAD_RITUAL_MSG3", 19);

            addLineSafe(lines_with_constant, "A small iron cauldron.", "USE_CAULDRON", 19);
            addLineSafe(lines_with_constant, "I found a shovel inside.", "TAKE_SHOVEL", 19);
            addLineSafe(lines_with_constant, "The chest is empty.", "TAKE_SHOVEL2", 19);
            addLineSafe(lines_with_constant, "An iron shovel.", "USE_SHOVEL", 19);
            addLineSafe(lines_with_constant, "What?! that statue is moving!", "MINI_BOSS_MSG1", 19);
            
            addLineSafe(lines_with_constant, "A human!!", "ENDING_VIGNETTE1_1",16);
            addLineSafe(lines_with_constant, "How did you get here?!", "ENDING_VIGNETTE1_2",16);
            
            addLineSafe(lines_with_constant, "You will never find out!", "ENDING_VIGNETTE2_1", 16);
            addLineSafe(lines_with_constant, "Die foul creature!!", "ENDING_VIGNETTE2_2", 16);
            
            addLineSafe(lines_with_constant, "I can hear Lucy behind that door!", "FINAL_PASSAGE1", 19);
            addLineSafe(lines_with_constant, "I can sneak up on her from here!", "FINAL_PASSAGE2", 19);
            addLineSafe(lines_with_constant, "Wait, I don't have a stake ready!", "FINAL_PASSAGE3", 19);
            
            addLineSafe(lines_with_constant, "I did it!", "ENDING_VIGNETTE3_1", 16);
            addLineSafe(lines_with_constant, "Lucy is dead!", "ENDING_VIGNETTE3_2", 16);
            
            addLineSafe(lines_with_constant, "I can't believe I'm doing this... But", "OPEN_GRAVE1", 19);
            addLineSafe(lines_with_constant, "I need to make sure Quincey's dead", "OPEN_GRAVE2", 19);
            addLineSafe(lines_with_constant, "and there are no more vampires", "OPEN_GRAVE3", 19);
            addLineSafe(lines_with_constant, "Well, he's dead alright.", "OPEN_GRAVE4", 19);
            
            addLineSafe(lines_with_constant, "This clay could be useful.", "CLAY_INTERACT1", 19);
            addLineSafe(lines_with_constant, "I should take it.", "CLAY_INTERACT2", 19);
            addLineSafe(lines_with_constant, "A small pile of clay.", "CLAY", 19);
            addLineSafe(lines_with_constant, "I found this key in Quincey's body.", "QUINCEY_KEY", 19);
            
            addLineSafe(lines_with_constant, "There was a key and a note inside!", "QUINCEY_CHEST", 19);

            addLineSafe(lines_with_constant, "If someone finds this, please complete the", "QUINCEY_LETTER1", 24);
            addLineSafe(lines_with_constant, "task I left unfinished. The Westenra house", "QUINCEY_LETTER2", 24);
            addLineSafe(lines_with_constant, "hides an unspeakable abomination in a secret", "QUINCEY_LETTER3", 24);
            addLineSafe(lines_with_constant, "basement. This ungodly creature must be", "QUINCEY_LETTER4", 24);
            addLineSafe(lines_with_constant, "sent to where it belongs... to hell!", "QUINCEY_LETTER5", 24);
            addLineSafe(lines_with_constant, "This is the key to its cell. But be careful", "QUINCEY_LETTER6", 24);
            addLineSafe(lines_with_constant, "for this is no ordinary creature... only silver", "QUINCEY_LETTER7", 24);
            addLineSafe(lines_with_constant, "bullets can harm it. I hope someone braver", "QUINCEY_LETTER8", 24);
            addLineSafe(lines_with_constant, "than me can finish this task...", "QUINCEY_LETTER9", 24);
            addLineSafe(lines_with_constant, "Quincey Morris", "QUINCEY_LETTER10", 24);
            
            addLineSafe(lines_with_constant, "Maybe I can make silver bullets", "MELT_CUTLERY1", 19);
            addLineSafe(lines_with_constant, "melting this in the cauldron!", "MELT_CUTLERY2", 19);

            addLineSafe(lines_with_constant, "I could make a silver bullet mold", "CLAY_WET1", 19);
            addLineSafe(lines_with_constant, "with this, but it's too dry to work.", "CLAY_WET2", 19);
            addLineSafe(lines_with_constant, "I could make the clay wet here, but", "CLAY_WET3", 19);
            addLineSafe(lines_with_constant, "I need a bullet to make the mold.", "CLAY_WET4", 19);

            addLineSafe(lines_with_constant, "I made the clay wet and put a", "CLAY_WET5", 19);
            addLineSafe(lines_with_constant, "bullet from my gun inside to make a", "CLAY_WET6", 19);
            addLineSafe(lines_with_constant, "mold. I now need to cook the clay.", "CLAY_WET7", 19);
            addLineSafe(lines_with_constant, "A bullet mold, it's still wet.", "WET_MOLD", 19);

            addLineSafe(lines_with_constant, "I cooked the clay in the fireplace, I", "MOLD_COOK1", 19);
            addLineSafe(lines_with_constant, "now just need some melted silver!", "MOLD_COOK2", 19);
            addLineSafe(lines_with_constant, "A bullet mold.", "MOLD", 19);

            addLineSafe(lines_with_constant, "I could melt the silver, but I need", "MELT_SILVER1", 19);
            addLineSafe(lines_with_constant, "a mold to make the bullets.", "MELT_SILVER2", 19);

            addLineSafe(lines_with_constant, "I made several silver bullets by", "MELT_SILVER3", 19);
            addLineSafe(lines_with_constant, "melting the silver into the mold!", "MELT_SILVER4", 19);

            addLineSafe(lines_with_constant, "Some silver bullets.", "SILVER_BULLETS", 19);

            addLineSafe(lines_with_constant, "This must be the creature Quincey", "FRANKY1", 19);
            addLineSafe(lines_with_constant, "described!", "FRANKY2", 19);
            addLineSafe(lines_with_constant, "That does not seem to harm it!", "FRANKY3", 19);
            addLineSafe(lines_with_constant, "Quincey can rest in peace now.", "FRANKY4", 19);
            addLineSafe(lines_with_constant, "I completed his task...", "FRANKY5", 19);
            addLineSafe(lines_with_constant, "I love you father", "FRANKY_LETTER1", 19);
            
            addLineSafe(lines_with_constant, "Vampires killed:", "VAMPIRES_KILLED", 16);
            addLineSafe(lines_with_constant, "Secondary mission progress:", "SECONDARY_PROGRESS", 16);

            addLineSafe(lines_with_constant, "A log book, I'll write something.", "LOG_BOOK1", 19);
            addLineSafe(lines_with_constant, "- GAME SAVED -", "LOG_BOOK2", 19);
            addLineSafe(lines_with_constant, "Continue from saved game?", "CONTINUE1", 19);
            addLineSafe(lines_with_constant, "yes", "CONTINUE2", 19);
            addLineSafe(lines_with_constant, "no", "CONTINUE3", 19);

        } else {
            // Sentences in the original, not in EX:
            addLineSafe(lines_with_constant, "This must be Lucy!", "ENTER_VAMPIRE3_ROOM1", 19);
            addLineSafe(lines_with_constant, "I did it! Lucy is dead!", "ENTER_VAMPIRE3_ROOM2", 19);
        }
        
//        // Generate text spreadsheet:
//        {
//            List<String> allConstants = new ArrayList<>();
//            HashMap<String,String> constantToLine = new HashMap<>();
//            for(String line:lines_with_constant.keySet()) {
//                allConstants.add(lines_with_constant.get(line));
//                constantToLine.put(lines_with_constant.get(line), line);
//            }
//            Collections.sort(allConstants);
//            for(String constant:allConstants) {
//                System.out.println(constant + "\t" + constantToLine.get(constant));
//            }
//        }
            
        List<Integer> capitals = font.convertStringToAssembler("ABCDEFGHIJKLMNOPQRSTUVWXYZ ");
        System.out.println("Capitals: " + capitals);
        List<Integer> puzzleMessage = font.convertStringToAssembler("VladalIIIleaTepes");
        System.out.println("puzzleMessage: " + puzzleMessage);        
        System.out.println("English: " + font.convertStringToAssembler("English"));        
        System.out.println("Español: " + font.convertStringToAssembler("Español"));        
        
        for(String s:lines_with_constant.keySet()) {
            if (!lines.contains(s)) lines.add(s);
        }


        // List<String> newlines = lines;
        int textBankSize = 640;
//        List<String> newlines = optimizeGrouppings(lines, font, 512, 8000);
        List<String> newlines = optimizeGrouppings(lines, font, textBankSize, 7800);
        // List<String> newlines = optimizeGrouppings(lines, font, 600);
        // List<String> newlines = optimizeGrouppings(lines, font, 640);
        // List<String> newlines = optimizeGrouppings(lines, font, 700);
//         List<String> newlines = optimizeGrouppings(lines, font, 4096);
        
        HashMap<String, Pair<Integer, Integer>> ids = new HashMap<>();
        Pair<List<Integer>,List<Integer>> sizes = EncodeText.encodeTextInBanks(newlines, font, textBankSize, "src/autogenerated", "textBank", ids, "zx0");
        int size_before = 0;
        int size_after = 0;
        for(Integer size:sizes.m_a) size_before += size;
        for(Integer size:sizes.m_b) size_after += size;
        System.out.println("Total size before: " + size_before);
        System.out.println("Total size after: " + size_after);
        // String constants:
        {
            FileWriter fw = new FileWriter(new File("src/autogenerated/text-constants.asm"));
            for(String s:lines_with_constant.keySet()) {
                fw.write("TEXT_"+lines_with_constant.get(s)+"_BANK:   equ " + ids.get(s).m_a + "\n");
                fw.write("TEXT_"+lines_with_constant.get(s)+"_IDX:   equ " + ids.get(s).m_b + "\n");            
            }
            fw.flush();
            fw.close();
        }
    }
    
    
    public static void addLineSafe(HashMap<String,String> lines_with_constant, String line, String tag, int maxWidthInTiles) throws Exception
    {
        if (font.stringWidth(line) > maxWidthInTiles*8) {
            throw new Exception("'"+line+"' is wider than " + maxWidthInTiles + " tiles! (" + font.stringWidth(line) + " pixels, vs " + maxWidthInTiles*8 + ")");
        }
        lines_with_constant.put(line, tag);
    }
        
    
    public static List<String>  optimizeGrouppings(List<String> input_lines, PAKFont font, int group_size, int target_size) throws Exception
    {
        List<String> bestLines = null;
//        EncodeText.compressor = "zx0";
        int best_size = 0;
        int best_seed = 0;      // seed 234: 1899 (for group_size 512, with 0.5 lateral moves)
                                // seed 0: 1903 (for group size 600)
                                // seed 3: 1874 (for group size 640)
                                // seed 6: 1850 (for group size 700)
        for(int seed = 0;seed<0+1;seed++) {
//        for(int seed = 0;seed<1000;seed++) {
//        for(int seed = 234;seed<234+1;seed++) {
//            int max_repeats = 20;
            int max_repeats = 5;
            Pair<List<String>,Integer> tmp = optimizeGrouppingsInternal(input_lines, font, group_size, seed, max_repeats, target_size);
            if (bestLines == null || tmp.m_b < best_size) {
                bestLines = tmp.m_a;
                best_size = tmp.m_b;
                best_seed = seed;
                System.out.println("new best_size: " + best_size + " (best_seed: " + best_seed + ")");
            }
        }
        
        System.out.println("final best_size: " + best_size + " (best_seed: " + best_seed + ")");
        return bestLines;
    }
    
    
    public static Pair<List<String>,Integer>  optimizeGrouppingsInternal(List<String> input_lines, PAKFont font, int group_size, int seed, int max_repeats, int target_size) throws Exception  
    {
        String compressorDuringOptimization = "pletter";
        String targetCompressor = "zx0";
        Random r = new Random();
        r.setSeed(seed);

        List<String> lines = new ArrayList<>();
        lines.addAll(input_lines);
        Collections.shuffle(lines, r);
        int initial_size = EncodeText.estimateSizeOfAllTextBanks(lines, font, group_size, compressorDuringOptimization);
        int best = initial_size;
        System.out.println("Original order size: " + initial_size + " (with target compressor: " + 
                EncodeText.estimateSizeOfAllTextBanks(lines, font, group_size, targetCompressor) + ")");
        System.out.println("Initial size (seed " + seed + "):" + initial_size);

        double threshold = 1.0; // 1.0 means doing it sistematically, lower values run faster, but might not result in the best results
        double temperature = 0.0;
        double temperature_decay = 0.8;
        boolean repeat = true;
        // boolean repeat = false;
        int repeats_left = max_repeats;
        while(repeat){
            repeat = false;
            System.out.println("temperature: " + temperature);
            for(int idx1 = 0;idx1<lines.size();idx1++) {
                // System.out.println(idx1 + "");
                for(int idx2 =idx1+1;idx2<lines.size();idx2++) {
                    if (r.nextDouble() > threshold) continue;
                    String tmp1 = lines.get(idx1);
                    String tmp2 = lines.get(idx2);
                    lines.set(idx1, tmp2);
                    lines.set(idx2, tmp1);

                    int size = EncodeText.estimateSizeOfAllTextBanks(lines, font, group_size, compressorDuringOptimization);
                    if (size < best) {
                        System.out.print(size + " ");
                        best = size;
                        repeat = true;
                    } else if (size == best && r.nextDouble() > 0.5) {
                        System.out.print(size + "* ");
                        best = size;
                        // repeat = true;
                    } else {
                        if (r.nextDouble() > temperature) {
                            // undo the swap:
                            lines.set(idx1, tmp1);
                            lines.set(idx2, tmp2);
                        } else {
                            System.out.println("- temperature ("+temperature+") induced random swap: " + size);
                            best = size;
                            repeat = true;                            
                        }
                    }
                    if (best <= target_size) break;            
                }
                if (best <= target_size) break;            
            }
            System.out.println("");
            temperature *= temperature_decay;
            /*
            if (!repeat && !compressorDuringOptimization.equals(targetCompressor)) {
                // At the end do one round with the target compressor:
                compressorDuringOptimization = targetCompressor;
                best = EncodeText.estimateSizeOfAllTextBanks(lines, font, group_size, targetCompressor);
                repeat = true;
            }*/
            // repeat = false;
            repeats_left--;
            if (repeats_left <= 0) break;
            if (best <= target_size) break;
        }
        
        // System.out.println(lines);
        System.out.println("After optimization: " + EncodeText.estimateSizeOfAllTextBanks(lines, font, group_size, targetCompressor));
        
        return new Pair<>(lines, best);
    }
}
