    include "constants.asm"
; IF LANGUAGE = 2
;     include "autogenerated/text-constants-ptbr.asm"
; ELSE
; IF LANGUAGE = 1
;     include "autogenerated/text-constants-es.asm"
; ELSE
;     include "autogenerated/text-constants.asm"
; ENDIF
; ENDIF

;-----------------------------------------------
; pages:
; 0: #4000 - 5ffff: core code
; 1: #6000 - 7ffff: core code
; 2: #8000 - #9fff: swapeable code 1
; 3: #a000 - #bfff: swapeable code 2
; 4: #a000 - #bfff: object data 1
; 5: #a000 - #bfff: object data 2
; 6: #a000 - #bfff: object data 3
; 7: #a000 - #bfff: sprite data
; 8: #a000 - #bfff: maps and other data
; 9: #a000 - #bfff: music bank 1
; 10: #a000 - #bfff: music bank 2 + SFX
; 11: #a000 - #bfff: music bank 3
; 12: #a000 - #bfff: music bank 4
; 13: #a000 - #bfff: text english
; 14: #a000 - #bfff: graphic data
; 15: #a000 - #bfff: text spanish

;-----------------------------------------------
; PAGES 0/1:
    org #4000   ; Start in the 2nd slot
start_of_pages_0_1:


;-----------------------------------------------
    db "AB"     ; ROM signature
    dw Execute  ; start address
    db 0,0,0,0,0,0,0,0,0,0,0,0
;-----------------------------------------------


;-----------------------------------------------
; - We will always leave pages 0 and 1 mapped to #4000 - 7fff
; - This macro changes which pages are mapped to #8000 - 9fff
SETMEGAROMPAGES:    MACRO ?p1, ?p2
    ld a, ?p1
    ld (current_megarom_page_in_8000), a
    ld (#8000), a
    ld a, ?p2
    ld (current_megarom_page_in_a000), a
    ld (#a000), a
    ENDM


;-----------------------------------------------
; - This macro changes which page is mapped to #8000 - 9fff
SETMEGAROMPAGE_8000:    MACRO ?p1
    ld a, ?p1
    ld (current_megarom_page_in_8000), a
    ld (#8000), a
    ENDM


;-----------------------------------------------
; - We will always leave pages 0 and 1 mapped to #4000 - 7fff
; - This macro changes which page is mapped to #a000 - bfff
SETMEGAROMPAGE_A000:    MACRO ?p2
    ld a, ?p2
    ld (current_megarom_page_in_a000), a
    ld (#a000), a
    ENDM


SETMEGAROMPAGE_A000_A:    MACRO
    ld (current_megarom_page_in_a000), a
    ld (#a000), a
    ENDM


;-----------------------------------------------
; Code that gets executed when the game starts
Execute:
    di
    ; init the stack:
    ld sp,#F380
    ; reset some interrupts to make sure it runs in some MSX computers 
    ; with disk controllers installed in some interrupt handlers
    ld a,#C9
    ld (HKEY),a
    ld (TIMI),a
    ei

    call SETPAGES32K

    ; select the appropriate pages: 0-1-2-4
    ld a,1
    ld (#6000),a
    SETMEGAROMPAGES 2,4

    ; Silence, init keyboard, and clear config:
    xor a
    ld (RAM_game_saved),a  ; mark that there is no game saved
    ld (CLIKSW),a
    ; Change background colors:
    ld (BAKCLR),a
    ld (BDRCLR),a
    call CHGCLR

    ld a,2      ; Change screen mode
    call CHGMOD

    ;; 16x16 sprites:
    ld bc,#e201  ;; write #e2 in VDP register #01 (activate sprites, generate interrupts, 16x16 sprites with no magnification)
    call WRTVDP

    call CheckIf60Hz
    ld (isComputer50HzOr60Hz),a ; 0: 50Hz, 1: 60Hz
    ld hl,interrupt_tempo_speed
    or a
    jr z,Execute_set_song_speeds_50Hz
Execute_set_song_speeds_60Hz:
    ld (hl),107
    jr Execute_song_speeds_set
Execute_set_song_speeds_50Hz:
    ld (hl),128
Execute_song_speeds_set:

    ; set default key mapping:
    ld hl,key_to_direction_mapping
    ld (key_to_direction_mapping_ptr),hl

    ; Init sound engine:
    call wyz_player_init
    ld hl,SFX_player_active
    ld (hl),0
    call setup_custom_interrupt

    jp state_language_selection


;-----------------------------------------------
; input:
; - hl: address to call in page 3
; modifies:
; - a
call_from_page_3_and_back_to_previous:
    ld a,(current_megarom_page_in_8000)
    push af
        SETMEGAROMPAGE_8000 3
        push de
            ld de,call_from_page_3_and_back_to_2_ret
            push de
            jp hl
call_from_page_3_and_back_to_2_ret:
        pop de
    pop af
    ld (current_megarom_page_in_8000),a
    ld (#8000),a
    ret


;-----------------------------------------------
; additional source code assembler files:
    include "auxiliar.asm"
    include "dzx0_standard.asm"
    include "input.asm"
    include "gfx.asm"
    include "gfx-bitmap.asm"
    include "interrupt.asm"
    include "text.asm"
    include "hud.asm"
    include "room-load.asm"
    include "room-draw.asm"
    include "player.asm"
    include "inventory.asm"
    include "collision.asm"
    include "state-dispatcher.asm"
    include "sound.asm"
    include "wyzplayer47d-fast.asm"
EndofCode:

;-----------------------------------------------
; This is here, so it's accessible without any megarom page switch
bullet_bin:
    db 1, 1, 8, 8, 8, 0, 0  ; object width, height, etc.
    db 0xff, 0x00
    db 0xc3, 0x00
    db 0x81, 0x00
    db 0x81, 0x18
    db 0x81, 0x18
    db 0x81, 0x00
    db 0xc3, 0x00
    db 0xff, 0x00

    db 0xff, 0x00
    db 0xff, 0x00
    db 0xff, 0x00
    db 0xff, 0x00
    db 0xff, 0x00
    db 0xff, 0x00
    db 0xff, 0x00
    db 0xff, 0x00    

;-----------------------------------------------
; Yes, if you are looking into the source code for clues on the pass words for the 
; vampire doors, here you have them :)
password_vampire1_en:  ; JULY
    db 9,20,11,24,26,26
password_vampire1_es:  ; JULIO
    db 9,20,11,8,14,26
password_vampire2:  ; WESTEN
    db 22,4,18,19,4,13
password_vampire3:  ; AHJSQM
    db 0,7,9,18,16,12
password_vampire4:  ; LUCARD
    db 11,20,2,0,17,3
password_puzzlebox:  ; ARDEAL
    db 0,17,3,4,0,11


    include "autogenerated/music/instruments.asm"

end_of_pages_0_1:
    ds #8000-$

;-----------------------------------------------
; PAGE 2: swapeable code 1
    org #8000
start_of_page_2:

    include "objects.asm"
    include "enemies.asm"
    include "skeleton-boss.asm"
    include "franky-boss.asm"

    include "state-gamestart.asm"
    include "state-game.asm"
    include "state-intro.asm"
    include "state-cutscene-family.asm"
    include "state-cutscene-lucy.asm"
    include "state-cutscene-vlad-ritual.asm"


IF CHEATS_ON = 1
    include "cheats.asm"
ENDIF

end_of_page_2:
    ds #a000-$


;-----------------------------------------------
; PAGE 3: swapeable code 2
    org #8000
start_of_page_3:

    include "floors.asm"
    include "walls.asm"
    include "doors.asm"
    include "switches.asm"
    include "room-colliders.asm"

    include "hud-page3.asm"    

    ; Code for states that do not require "objects.asm" or "enemies.asm":
    include "state-title.asm"
    include "state-gameover.asm"
    include "state-puzzle-vampire-name.asm"
    include "state-puzzle-chapel.asm"
    include "state-puzzle-box.asm"
    include "state-ending.asm"
    include "state-tutorial.asm"
    include "state-cutscene-travel.asm"    
    include "continue.asm"
    include "state-language-selection.asm"    

; end_of_page_3:
;     ds #a000 - $
end_of_page_3:
    ds (#a000 - (konami_mark_end - konami_mark_start)) - $

; Fake Konami title and RC number :) (see https://msx.org/forum/msx-talk/software/some-konami-roms-include-the-game-title-and-rc-number)
konami_mark_start:
    db "EX ESUOH NETSEW",#0f,#67,#AA
konami_mark_end:


;-----------------------------------------------
; PAGE 4: object data (1/3)
    org #a000
start_of_page_4:


object_data_ptrs:
    dw object_stool_zx0
    dw object_chair_left_zx0
    dw object_chair_right_zx0
    dw object_table1_zx0
    dw object_table2_zx0
    dw object_tombstone_zx0
    dw object_doorframe_bookshelf_left_zx0
    dw object_doorframe_bookshelf_right_zx0
    dw object_doorframe_brick_left_zx0  ; 10
    dw object_doorframe_brick_right_zx0
    dw object_stairs_nw_1_zx0
    dw object_stairs_nw_2_zx0
    dw object_yellow_key_zx0
    dw object_door_left_zx0
    dw object_door_right_zx0
;     dw object_gun_zx0
    dw object_gun_key_zx0
    dw object_clock_right_zx0
    dw object_fence_zx0
    dw object_stone_zx0  ; 20
    dw object_flower_zx0
    dw object_column_zx0
    dw object_platform1_zx0
    dw object_platform2_zx0
    dw object_door_right_zx0
    dw object_doorframe_entrance_right_zx0
    dw object_stair_steps_right_zx0
    dw object_stair_steps_rail_zx0
    dw object_doorframe_wood_left_zx0
    dw object_doorframe_wood_right_zx0  ; 30
    dw object_chest_zx0
    dw object_painting_right_zx0
    dw object_hanger_zx0
    dw object_vase_zx0
    dw object_night_table_zx0
    dw object_dining_table_1_zx0
    dw object_dining_table_2_zx0
    dw object_crate_zx0
    dw object_couch_zx0
    dw object_window_ne_zx0  ; 40
    dw object_barrel_zx0
    dw object_shelves_nw_zx0
    dw object_sink_zx0
    dw object_letter3_zx0
    dw object_lamp_zx0
    dw object_oil_zx0
    dw object_painting_right_zx0
    dw object_safe_right_zx0
    dw object_spiderweb_zx0
    dw object_toilet_zx0  ; 50
    dw object_chest2_zx0
    dw object_bathtub_zx0
    dw object_gramophone_zx0
    dw object_violin_zx0    
    dw object_heart_zx0
    dw object_heart_zx0
    dw object_bookstack_zx0
    dw object_writing_table_1_zx0
    dw object_writing_table_2_zx0
    dw object_book_zx0  ; 60
    dw object_tallcrate_zx0
    dw object_tallstool_zx0
    dw object_candle_zx0
    dw object_candle_zx0
    dw object_candle_zx0
    dw object_pentagram1_zx0
    dw object_pentagram2_zx0
    dw object_door_right_zx0
    dw object_brickwall_zx0
    dw object_grid_zx0
    dw object_column_blue_zx0
    dw object_spikes_zx0
    dw object_blue_brick_zx0
    dw object_torch_zx0
    dw object_bones1_zx0
    dw object_bones2_zx0
    dw object_bones3_zx0
    dw object_coffin1_zx0
    dw object_coffin2_zx0
    dw object_door_left_zx0  ; 80
    dw object_chest_gun_zx0
    dw object_book_zx0
    dw object_door_vampire_zx0
    dw object_door_vampire_zx0
    dw object_door_vampire_zx0
    dw object_red_carpet_zx0
    dw object_altar_zx0
    dw object_cross_zx0
    dw object_door_right_zx0
    dw object_green_key_zx0  ; 90
    dw object_carpet_1_zx0
    dw object_carpet_2_zx0
    dw object_fireplace_zx0  ; 93 <- first to be in page 5
    dw object_window_nw_zx0
    dw object_bed_1_zx0
    dw object_bed_2_zx0
    dw object_heart_page2_zx0
    dw object_diary1_zx0
    dw object_diary2_zx0
    dw object_diary3_zx0  ; 100
    dw object_lab_bottle_zx0
    dw object_lab_bottles_zx0
    dw object_lab_notes_zx0
    dw object_hammer_zx0
    dw object_crate_breakable_zx0
    dw object_crate_breakable_zx0
    dw object_crate_breakable_zx0
    dw object_crate_breakable_zx0
    dw object_crate_breakable_zx0
    dw object_crate_breakable_zx0  ; 110
    dw object_door_right_page5_zx0
    dw object_garlic_zx0
    dw object_garlic_zx0
    dw object_garlic_zx0
    dw object_stake_zx0
    dw object_stake_zx0
    dw object_stake_zx0
    dw object_fence2_zx0
    dw object_bookshelves_nw_zx0
    dw object_night_table_nw_zx0 ; 120
    dw object_bookstack_home_zx0
    dw object_luggage_zx0
    dw object_newspaper_zx0
    dw object_university_notes_zx0
    dw object_door_right_page5_zx0
    dw object_doorstep_zx0
    dw object_door_left_page5_zx0
    dw 0  ; collider event
    dw object_streetlamp_zx0
    dw object_streetlamp_wall_zx0 ; 130
    dw object_street_corner_zx0
    dw object_watkins_column_zx0
    dw object_watkins_sign_zx0
    dw object_watkins_door_zx0
    dw object_horsecar_zx0
    dw object_horse_zx0
    dw object_beggar_zx0
    dw object_beggar_bag_zx0
    dw object_beggar_dead_zx0
    dw object_bookshelves_nw_zx0 ; 140
    dw object_bookstack_home_zx0
    dw object_bookstore_clerk_zx0
    dw object_bookshelves_nw_zx0
    dw object_choffeur_zx0
    dw object_lucy_torn_note_zx0
    dw object_secret_staircase_zx0
    dw object_sarcophagus_zx0
    dw object_doorframe_gothic_left_zx0
    dw object_doorframe_gothic_right_zx0
    dw object_vlad_statue_zx0
    dw object_suit_of_armor_nw_zx0
    dw object_suit_of_armor_ne_zx0
    dw object_suit_of_armor_sw_zx0
    dw object_banner_nw_zx0
    dw object_banner_ne_zx0
    dw object_dinner_table_middle_zx0
    dw object_chair_ne_zx0
    dw object_chair_sw_zx0
    dw object_door_vampire4_zx0
    dw object_coin_pile_zx0
    dw object_bookshelves_nw_zx0
    dw object_puzzle_box_zx0
    dw object_tall_black_brick_zx0
    dw object_desk_ne_zx0
    dw object_vlad_diary_zx0
    dw object_black_stairs_nw_zx0
    dw object_bookstack_home_zx0
    dw object_mirror_zx0
    dw object_mirror_ne_zx0
    dw object_mirror_clue_zx0
    dw object_chest_reveal_zx0
    dw object_chest_reveal_zx0
    dw object_chest_reveal_zx0
    dw object_door_prison_ne_zx0  ; entrance
    dw object_door_prison_ne_zx0  ; franky
    dw object_door_prison_ne_zx0  ; passage
    dw object_vlad_ritual_zx0
    dw object_grid2_zx0
    dw object_skeleton_ne_zx0
    dw object_cauldron_zx0
    dw object_switch_zx0
    dw object_chest_reveal_zx0
    dw object_brickwall_thin_zx0  ; 183 <- first to be in page 6
    dw object_arrow_shooter_zx0
    dw object_arrow_shooter_zx0
    dw object_skeleton_boss_zx0
    dw object_skeleton_key_zx0
    dw object_heart_page3_zx0
    dw object_open_grave_zx0
    dw object_clay_zx0
    dw object_log_book_zx0
    dw object_franky_zx0
    dw object_franky_note_zx0

object_stool_zx0:
    incbin "autogenerated/objects/stool.zx0"
object_chair_left_zx0:
    incbin "autogenerated/objects/chair-left.zx0"
object_chair_right_zx0:
    incbin "autogenerated/objects/chair-right.zx0"
object_table1_zx0:
    incbin "autogenerated/objects/table-1.zx0"
object_table2_zx0:
    incbin "autogenerated/objects/table-2.zx0"
object_tombstone_zx0:
    incbin "autogenerated/objects/tombstone.zx0"
object_doorframe_bookshelf_left_zx0:
    incbin "autogenerated/objects/doorframe-bookshelf-left.zx0"
object_doorframe_bookshelf_right_zx0:
    incbin "autogenerated/objects/doorframe-bookshelf-right.zx0"
object_doorframe_brick_left_zx0:
    incbin "autogenerated/objects/doorframe-brick-left.zx0"
object_doorframe_brick_right_zx0:
    incbin "autogenerated/objects/doorframe-brick-right.zx0"
object_stairs_nw_1_zx0:
    incbin "autogenerated/objects/stairs-nw-1.zx0"
object_stairs_nw_2_zx0:
    incbin "autogenerated/objects/stairs-nw-2.zx0"
object_yellow_key_zx0:
    incbin "autogenerated/objects/yellow-key.zx0"
object_door_left_zx0:
    incbin "autogenerated/objects/door-left.zx0"
object_door_right_zx0:
    incbin "autogenerated/objects/door-right.zx0"
; object_gun_zx0:
;     incbin "autogenerated/objects/gun.zx0"
object_gun_key_zx0:
    incbin "autogenerated/objects/gun-key.zx0"
object_clock_right_zx0:
    incbin "autogenerated/objects/clock-right.zx0"
object_fence_zx0:
    incbin "autogenerated/objects/fence.zx0"
object_stone_zx0:
    incbin "autogenerated/objects/stone.zx0"
object_flower_zx0:
    incbin "autogenerated/objects/flower.zx0"
object_column_zx0:
    incbin "autogenerated/objects/column.zx0"
object_platform1_zx0:
    incbin "autogenerated/objects/platform1.zx0"
object_platform2_zx0:
    incbin "autogenerated/objects/platform2.zx0"
object_doorframe_entrance_right_zx0:
    incbin "autogenerated/objects/doorframe-entrance-right.zx0"
object_stair_steps_right_zx0:
    incbin "autogenerated/objects/stair-steps-right.zx0"
object_stair_steps_rail_zx0:
    incbin "autogenerated/objects/stair-steps-rail.zx0"
object_doorframe_wood_left_zx0:
    incbin "autogenerated/objects/doorframe-wood-left.zx0"
object_doorframe_wood_right_zx0:
    incbin "autogenerated/objects/doorframe-wood-right.zx0"
object_chest_zx0:
    incbin "autogenerated/objects/chest.zx0"
object_painting_right_zx0:
    incbin "autogenerated/objects/painting-right.zx0"
object_hanger_zx0:
    incbin "autogenerated/objects/hanger.zx0"
object_vase_zx0:
    incbin "autogenerated/objects/vase.zx0"
object_night_table_zx0:
    incbin "autogenerated/objects/night-table.zx0"
object_dining_table_1_zx0
    incbin "autogenerated/objects/dining-table-1.zx0"
object_dining_table_2_zx0
    incbin "autogenerated/objects/dining-table-2.zx0"
object_crate_zx0:
    incbin "autogenerated/objects/crate.zx0"
object_couch_zx0:
    incbin "autogenerated/objects/couch.zx0"
object_window_ne_zx0:
    incbin "autogenerated/objects/window-ne.zx0"
object_barrel_zx0:
    incbin "autogenerated/objects/barrel.zx0"
object_shelves_nw_zx0:
    incbin "autogenerated/objects/shelves-nw.zx0"
object_sink_zx0:
    incbin "autogenerated/objects/sink.zx0"
object_letter3_zx0:
    incbin "autogenerated/objects/letter3.zx0"
object_lamp_zx0:
    incbin "autogenerated/objects/lamp.zx0"
object_oil_zx0:
    incbin "autogenerated/objects/oil.zx0"
object_safe_right_zx0:
    incbin "autogenerated/objects/safe-right.zx0"
object_spiderweb_zx0:
    incbin "autogenerated/objects/spiderweb.zx0"
object_toilet_zx0:
    incbin "autogenerated/objects/toilet.zx0"
object_chest2_zx0:
    incbin "autogenerated/objects/chest2.zx0"
object_bathtub_zx0:
    incbin "autogenerated/objects/bathtub.zx0"
object_gramophone_zx0:
    incbin "autogenerated/objects/gramophone.zx0"
object_violin_zx0:
    incbin "autogenerated/objects/violin.zx0"
object_heart_zx0:
    incbin "autogenerated/objects/heart.zx0"
object_bookstack_zx0:
    incbin "autogenerated/objects/bookstack.zx0"
object_writing_table_1_zx0
    incbin "autogenerated/objects/writing-table-1.zx0"
object_writing_table_2_zx0
    incbin "autogenerated/objects/writing-table-2.zx0"    
object_chest_gun_zx0:
    incbin "autogenerated/objects/chest-gun.zx0"
object_book_zx0:
    incbin "autogenerated/objects/book.zx0"
object_tallcrate_zx0:
    incbin "autogenerated/objects/tall-crate.zx0"
object_tallstool_zx0:
    incbin "autogenerated/objects/tall-stool.zx0"
object_candle_zx0:
    incbin "autogenerated/objects/candle.zx0"
object_pentagram1_zx0:
    incbin "autogenerated/objects/pentagram1.zx0"
object_pentagram2_zx0:
    incbin "autogenerated/objects/pentagram2.zx0"
object_brickwall_zx0:
    incbin "autogenerated/objects/brickwall.zx0"
object_grid_zx0:
    incbin "autogenerated/objects/grid.zx0"
object_column_blue_zx0:
    incbin "autogenerated/objects/column-blue.zx0"
object_spikes_zx0:
    incbin "autogenerated/objects/spikes.zx0"
object_blue_brick_zx0:
    incbin "autogenerated/objects/blue-brick.zx0"
object_torch_zx0:
    incbin "autogenerated/objects/torch.zx0"
object_bones1_zx0:
    incbin "autogenerated/objects/bones1.zx0"
object_bones2_zx0:
    incbin "autogenerated/objects/bones2.zx0"
object_bones3_zx0:
    incbin "autogenerated/objects/bones3.zx0"
object_coffin1_zx0:
    incbin "autogenerated/objects/coffin-1.zx0"
object_coffin2_zx0:
    incbin "autogenerated/objects/coffin-2.zx0"
object_door_vampire_zx0:
    incbin "autogenerated/objects/door-vampire-right.zx0"
object_red_carpet_zx0:
    incbin "autogenerated/objects/red-carpet.zx0"
object_altar_zx0:
    incbin "autogenerated/objects/altar.zx0"
object_cross_zx0:
    incbin "autogenerated/objects/cross.zx0"
object_green_key_zx0:
    incbin "autogenerated/objects/green-key.zx0"
object_carpet_1_zx0:
    incbin "autogenerated/objects/carpet-1.zx0"
object_carpet_2_zx0:
    incbin "autogenerated/objects/carpet-2.zx0"

end_of_page_4:
    ds #c000 - $


;-----------------------------------------------
; PAGE 5: object data (2/3)
    org #a000
start_of_page_5:

object_fireplace_zx0:
    incbin "autogenerated/objects/fireplace.zx0"
object_window_nw_zx0:
    incbin "autogenerated/objects/window-left.zx0"
object_bed_1_zx0:
    incbin "autogenerated/objects/bed-1.zx0"
object_bed_2_zx0:
    incbin "autogenerated/objects/bed-2.zx0"
object_diary1_zx0:
    incbin "autogenerated/objects/diary1.zx0"
object_diary2_zx0:
    incbin "autogenerated/objects/diary2.zx0"
object_diary3_zx0:
    incbin "autogenerated/objects/diary3.zx0"
object_lab_bottle_zx0:
    incbin "autogenerated/objects/lab-bottle.zx0"
object_lab_bottles_zx0:
    incbin "autogenerated/objects/lab-bottles.zx0"
object_lab_notes_zx0:
    incbin "autogenerated/objects/lab-notes.zx0"
object_hammer_zx0:
    incbin "autogenerated/objects/hammer.zx0"
object_crate_breakable_zx0:
    incbin "autogenerated/objects/crate-breakable.zx0"
object_garlic_zx0:
    incbin "autogenerated/objects/garlic.zx0"
object_stake_zx0:
    incbin "autogenerated/objects/stake.zx0"
object_fence2_zx0:
    incbin "autogenerated/objects/fence2.zx0"
coffin_vampire_1_zx0:
    incbin "autogenerated/objects/coffin-vampire-1.zx0"
coffin_vampire_2_zx0:
    incbin "autogenerated/objects/coffin-vampire-2.zx0"
object_bookshelves_nw_zx0:
    incbin "autogenerated/objects/bookshelves-nw.zx0"
object_night_table_nw_zx0:
    incbin "autogenerated/objects/night-table-nw.zx0"
object_bookstack_home_zx0:
    incbin "autogenerated/objects/bookstack-home.zx0"
object_luggage_zx0:
    incbin "autogenerated/objects/luggage.zx0"
object_newspaper_zx0:
    incbin "autogenerated/objects/newspaper.zx0"
object_university_notes_zx0:
    incbin "autogenerated/objects/university-notes.zx0"
object_door_right_page5_zx0:
    incbin "autogenerated/objects/door-right.zx0"
object_doorstep_zx0:
    incbin "autogenerated/objects/doorstep.zx0"
object_door_left_page5_zx0:
    incbin "autogenerated/objects/door-left.zx0"
object_streetlamp_zx0:
    incbin "autogenerated/objects/streetlamp.zx0"
object_streetlamp_wall_zx0:
    incbin "autogenerated/objects/streetlamp-wall.zx0"
object_street_corner_zx0:
    incbin "autogenerated/objects/street-corner.zx0"
object_watkins_column_zx0:
    incbin "autogenerated/objects/watkins-column.zx0"
object_watkins_sign_zx0:
    incbin "autogenerated/objects/watkins-sign.zx0"
object_watkins_door_zx0:
    incbin "autogenerated/objects/watkins-door.zx0"
object_horsecar_zx0:
    incbin "autogenerated/objects/horsecar.zx0"
object_horse_zx0:
    incbin "autogenerated/objects/horse.zx0"
object_beggar_zx0:
    incbin "autogenerated/objects/beggar.zx0"
object_beggar_bag_zx0:
    incbin "autogenerated/objects/beggar-bag.zx0"
object_beggar_dead_zx0:
    incbin "autogenerated/objects/beggar-dead.zx0"
object_bookstore_clerk_zx0:
    incbin "autogenerated/objects/bookstore-clerk.zx0"
object_choffeur_zx0:
    incbin "autogenerated/objects/choffeur.zx0"
object_lucy_torn_note_zx0:
    incbin "autogenerated/objects/lucy-torn-note.zx0"
object_secret_staircase_zx0:
    incbin "autogenerated/objects/secret-staircase.zx0"
object_sarcophagus_zx0:
    incbin "autogenerated/objects/sarcophagus.zx0"
object_doorframe_gothic_left_zx0:
    incbin "autogenerated/objects/doorframe-gothic-left.zx0"
object_doorframe_gothic_right_zx0:
    incbin "autogenerated/objects/doorframe-gothic-right.zx0"
object_vlad_statue_zx0:
    incbin "autogenerated/objects/vlad-statue.zx0"
object_suit_of_armor_nw_zx0:
    incbin "autogenerated/objects/suit-of-armor-nw.zx0"
object_suit_of_armor_ne_zx0:
    incbin "autogenerated/objects/suit-of-armor-ne.zx0"
object_suit_of_armor_sw_zx0:
    incbin "autogenerated/objects/suit-of-armor-sw.zx0"
object_banner_nw_zx0:
    incbin "autogenerated/objects/banner-nw.zx0"
object_banner_ne_zx0:
    incbin "autogenerated/objects/banner-ne.zx0"
object_dinner_table_middle_zx0
    incbin "autogenerated/objects/dining-table-middle.zx0"
object_chair_ne_zx0:
    incbin "autogenerated/objects/chair-ne.zx0"
object_chair_sw_zx0:
    incbin "autogenerated/objects/chair-sw.zx0"
object_door_vampire4_zx0:
    incbin "autogenerated/objects/door-vampire-nw.zx0"
object_coin_pile_zx0:
    incbin "autogenerated/objects/coin-pile.zx0"
object_puzzle_box_zx0:
    incbin "autogenerated/objects/puzzle-box.zx0"
object_tall_black_brick_zx0:
    incbin "autogenerated/objects/tall-black-brick.zx0"
object_desk_ne_zx0:
    incbin "autogenerated/objects/desk-ne.zx0"
object_vlad_diary_zx0:
    incbin "autogenerated/objects/vlad-diary.zx0"
object_black_stairs_nw_zx0:
    incbin "autogenerated/objects/black-stairs-nw.zx0"
object_mirror_zx0:
    incbin "autogenerated/objects/mirror.zx0"
object_mirror_ne_zx0:
    incbin "autogenerated/objects/mirror-ne.zx0"
object_mirror_clue_zx0:
    incbin "autogenerated/objects/mirror-clue.zx0"
object_heart_page2_zx0:
    incbin "autogenerated/objects/heart.zx0"
object_chest_reveal_zx0:
    incbin "autogenerated/objects/chest-gun.zx0"
object_door_prison_ne_zx0:
    incbin "autogenerated/objects/door-prison-ne.zx0"
object_vlad_ritual_zx0:
    incbin "autogenerated/objects/vlad-ritual.zx0"
object_grid2_zx0:
    incbin "autogenerated/objects/grid2.zx0"
object_skeleton_ne_zx0:
    incbin "autogenerated/objects/skeleton-ne.zx0"
object_cauldron_zx0:
    incbin "autogenerated/objects/cauldron.zx0"
object_switch_zx0:
    incbin "autogenerated/objects/switch.zx0"

end_of_page_5:
    ds #c000 - $


;-----------------------------------------------
; PAGE 6: object data (3/3) + ending vignettes + font + miltilingual tables
    org #a000
start_of_page_6:

object_brickwall_thin_zx0:
    incbin "autogenerated/objects/brickwall-thin.zx0"
object_arrow_shooter_zx0:
    incbin "autogenerated/objects/arrow-shooter.zx0"
object_skeleton_boss_zx0:
    incbin "autogenerated/enemies/skeleton.zx0"
object_skeleton_key_zx0:
    incbin "autogenerated/objects/skeleton-key.zx0"
object_heart_page3_zx0:
    incbin "autogenerated/objects/heart.zx0"
object_open_grave_zx0:
    incbin "autogenerated/objects/open-grave.zx0"
object_clay_zx0:
    incbin "autogenerated/objects/clay.zx0"
object_log_book_zx0:
    incbin "autogenerated/objects/log-book.zx0"
object_franky_zx0:
    incbin "autogenerated/enemies/franky.zx0"
object_franky_note_zx0:
    incbin "autogenerated/objects/franky-note.zx0"


skeleton_boss_frames_zx0:
    incbin "autogenerated/enemies/skeleton-data.zx0"

franky_boss_sprites_zx0:
    incbin "autogenerated/enemies/franky-sprites.zx0"
franky_boss_frames_zx0:
    incbin "autogenerated/enemies/franky-data.zx0"

ending_vignette1_zx0:
    incbin "autogenerated/ending-vignette1.zx0"
ending_vignette2_zx0:
    incbin "autogenerated/ending-vignette2.zx0"
ending_vignette3_zx0:
    incbin "autogenerated/ending-vignette3.zx0"

font:
; IF LANGUAGE = 2
;     incbin "autogenerated/font-ptbr.bin"
; ELSE
; IF LANGUAGE = 1
;     incbin "autogenerated/font-es.bin"
; ELSE
;     incbin "autogenerated/font.bin"
; ENDIF
; ENDIF
    incbin "autogenerated/font-es.bin"

    include "autogenerated/text-multilingual.asm"

end_of_page_6:
    ds #c000 - $


;-----------------------------------------------
; PAGE 7: Sprites and graphics that do not fit in page 6
    org #a000
start_of_page_7:

player_sprites_bin:
    incbin "autogenerated/player-sprites.bin"

player_sprite_attributes_ROM:
    db 0,0, 0,COLOR_BLACK
    db 0,0, 4,COLOR_BLACK
    db 0,0, 8,COLOR_YELLOW
    db 0,0,12,COLOR_DARK_RED
    db 0,0,16,COLOR_BLUE
    db 0,0,20,COLOR_WHITE
inventory_pointer_sprite_attributes_ROM:
    db 19*8-1,8,24,COLOR_WHITE

family_cutscene_sprites_zx0:
    incbin "autogenerated/cutscene-sprites.zx0"
lucy_cutscene_sprites_zx0:
    incbin "autogenerated/cutscene-lucy-sprites.zx0"

; Family cutscene:
family_sprites_attributes_ROM:
    ; Arthur:
    db 79,72,28,COLOR_BLACK
    db 95,72,32,COLOR_BLACK
    db 87,72,36,COLOR_YELLOW
    db 95,72,40,COLOR_DARK_BLUE
    ; John:
    db 101,98,44,COLOR_BLACK
    db 117,98,48,COLOR_BLACK
    db 101,98,52,COLOR_WHITE
    db 101,98,56,COLOR_LIGHT_RED
    db 117,98,60,COLOR_WHITE
    ; Lucy:
    db 65,104,64,COLOR_BLACK
    db 81,104,68,COLOR_BLACK
    db 69,104,72,COLOR_YELLOW
    db 69,104,76,COLOR_DARK_RED
    db 81,104,80,COLOR_GREEN

; Lucy cutscene:
lucy_sprites_attributes_ROM:
    db 60,192,28,COLOR_BLACK
    db 76,192,32,COLOR_BLACK
    db 64,192,36,COLOR_YELLOW
    db 64,192,40,COLOR_DARK_RED
    db 76,192,44,COLOR_GREEN

lucy_ritual_sprites_attributes_ROM:
    db 49,106,28+6*5*4,COLOR_BLACK
    db 65,106,32+6*5*4,COLOR_BLACK
    db 53,106,36+6*5*4,COLOR_YELLOW
    db 53,106,40+6*5*4,COLOR_DARK_RED
    db 65,106,44+6*5*4,COLOR_GREEN
;     db 30,104,28+6*5*4,COLOR_BLACK
;     db 46,104,32+6*5*4,COLOR_BLACK
;     db 34,104,36+6*5*4,COLOR_YELLOW
;     db 34,104,40+6*5*4,COLOR_DARK_RED
;     db 46,104,44+6*5*4,COLOR_GREEN

inventory_pointer_sprite:
    db #ff, #80, #80, #80, #80, #80, #80, #80
    db #80, #80, #80, #80, #80, #80, #80, #ff
    db #ff, #01, #01, #01, #01, #01, #01, #01
    db #01, #01, #01, #01, #01, #01, #01, #ff

keyword_lock_pointer_sprite:
    db #18, #18, #18, #7e, #3c, #18, #00, #00
    db #00, #00, #00, #00, #00, #00, #00, #00
    db #00, #00, #00, #00, #00, #00, #00, #00
    db #00, #00, #00, #00, #00, #00, #00, #00

object_sprites_zx0:
    incbin "autogenerated/object-sprites.zx0"

skeleton_boss_sprites_zx0:
    incbin "autogenerated/enemies/skeleton-sprites.zx0"

object_sprites_attributes_alley:
    db 63, 120, 28, COLOR_DARK_YELLOW
    db 79, 120, 32, COLOR_DARK_YELLOW

object_sprites_attributes_street3:
    db 76, 112, 44, COLOR_YELLOW

object_sprites_attributes_bookstore:
    db 55, 48, 36, COLOR_WHITE
    db 71, 48, 40, COLOR_BLUE

pentagram_clue_zx0:
    incbin "autogenerated/pentagram-clue.zx0"    

pentagram_clue2_zx0:
    incbin "autogenerated/pentagram-clue2.zx0"    

travel_cutscene_data_zx0:
    incbin "autogenerated/travel-cutscene.zx0"


end_of_page_7:
    ds #c000 - $

;-----------------------------------------------
; PAGE 8: maps and other data
    org #a000
start_of_page_8:

;-----------------------------------------------
; Ending graphics:

ending_scroll_zx0:
    incbin "autogenerated/ending-scroll.zx0"
ending_map1_zx0:
    incbin "autogenerated/ending-map1.zx0"
ending_map2_zx0:
    incbin "autogenerated/ending-map2.zx0"
ending_map3_zx0:
    incbin "autogenerated/ending-map3.zx0"
ending_map4_zx0:
    incbin "autogenerated/ending-map4.zx0"
ending_the_end_zx0:
    incbin "autogenerated/ending-the-end.zx0"


letter3_lines:
    dw TEXT_LETTER3_LINE1
    dw #ffff
    dw TEXT_LETTER3_LINE2
    dw TEXT_LETTER3_LINE3
    dw TEXT_LETTER3_LINE4
    dw TEXT_LETTER3_LINE5
    dw TEXT_LETTER3_LINE6
    dw TEXT_LETTER3_LINE7

diary1_lines:
    dw TEXT_DIARY1_LINE1
    dw #ffff
    dw TEXT_DIARY1_LINE2
    dw #ffff
    dw TEXT_DIARY1_LINE3
    dw TEXT_DIARY1_LINE4
    dw TEXT_DIARY1_LINE5
    dw TEXT_DIARY1_LINE6

diary2_lines:
    dw TEXT_DIARY2_LINE1
    dw #ffff
    dw TEXT_DIARY1_LINE2
    dw #ffff
    dw TEXT_DIARY2_LINE3
    dw TEXT_DIARY2_LINE4
    dw TEXT_DIARY2_LINE5
    dw TEXT_DIARY2_LINE6
    dw TEXT_DIARY2_LINE7

lab_notes_lines:
    dw TEXT_LETTER3_LINE1
    dw #ffff
    dw TEXT_LETTER4_LINE2
    dw TEXT_LETTER4_LINE3
    dw TEXT_LETTER4_LINE4
    dw TEXT_LETTER4_LINE5
    dw TEXT_LETTER4_LINE6
    dw TEXT_LETTER4_LINE7
    dw TEXT_LETTER4_LINE8
    dw TEXT_LETTER4_LINE9
    dw TEXT_LETTER4_LINE10
    dw TEXT_LETTER4_LINE11

lab_notes_lines2:
    dw TEXT_LETTER4_LINE12
    dw TEXT_LETTER4_LINE13
    dw TEXT_LETTER4_LINE14
    dw TEXT_LETTER4_LINE15
    dw TEXT_LETTER4_LINE16
    dw TEXT_LETTER4_LINE17
    dw TEXT_LETTER4_LINE18
    dw TEXT_LETTER4_LINE19
    dw #ffff
    dw TEXT_LETTER4_LINE20

lab_notes_lines3:
    dw TEXT_LETTER5_LINE0
    dw TEXT_LETTER5_LINE1
    dw TEXT_LETTER5_LINE2
    dw TEXT_LETTER5_LINE3
    dw TEXT_LETTER5_LINE4
    dw TEXT_LETTER5_LINE5
    dw TEXT_LETTER5_LINE6
    dw TEXT_LETTER5_LINE7
    dw TEXT_LETTER5_LINE8

vampire1_note_lines:
    dw TEXT_VAMPIRE1_NOTE1
    dw #ffff
    dw TEXT_VAMPIRE1_NOTE2
    dw #ffff
    dw TEXT_VAMPIRE1_NOTE3
    dw #ffff
    dw TEXT_VAMPIRE1_NOTE4
    dw TEXT_VAMPIRE1_NOTE5
    dw TEXT_VAMPIRE1_NOTE6

vampire2_note_lines:
    dw TEXT_VAMPIRE2_NOTE1
    dw TEXT_VAMPIRE2_NOTE2
    dw TEXT_VAMPIRE2_NOTE3
    dw #ffff
    dw TEXT_VAMPIRE2_NOTE4

vlad_note_lines:
    dw TEXT_PUZZLE_BOX_MSG_NOTE1
    dw #ffff
    dw TEXT_PUZZLE_BOX_MSG_NOTE2
    dw #ffff
    dw TEXT_PUZZLE_BOX_MSG_NOTE3
    dw #ffff
    dw TEXT_PUZZLE_BOX_MSG_NOTE4

travel_cutscene_1:
    dw TEXT_TRAVEL_CUTSCENE1
    dw #ffff
    dw TEXT_TRAVEL_CUTSCENE2

travel_cutscene_2a:
    dw TEXT_TRAVEL_CUTSCENE3A
    dw #ffff
    dw TEXT_TRAVEL_CUTSCENE4A

travel_cutscene_2b:
    dw TEXT_TRAVEL_CUTSCENE3B
    dw #ffff
    dw TEXT_TRAVEL_CUTSCENE4B

travel_cutscene_3b:
    dw TEXT_TRAVEL_CUTSCENE5B
    dw #ffff
    dw TEXT_TRAVEL_CUTSCENE6B
    dw #ffff
    dw TEXT_TRAVEL_CUTSCENE7B
    dw #ffff
    dw TEXT_TRAVEL_CUTSCENE8B

travel_cutscene_4b:
    dw TEXT_TRAVEL_CUTSCENE9B
    dw #ffff
    dw TEXT_TRAVEL_CUTSCENE10B
    dw #ffff
    dw TEXT_TRAVEL_CUTSCENE11B

vlad_diary_lines1:
    dw TEXT_VLAD_DIARY1
    dw TEXT_VLAD_DIARY2
    dw TEXT_VLAD_DIARY3
    dw TEXT_VLAD_DIARY4
    dw #ffff
    dw TEXT_VLAD_DIARY5
    dw TEXT_VLAD_DIARY6
    dw TEXT_VLAD_DIARY7
    dw TEXT_VLAD_DIARY8

vlad_diary_lines2:
    dw TEXT_VLAD_DIARY9
    dw TEXT_VLAD_DIARY10
    dw TEXT_VLAD_DIARY11
    dw TEXT_VLAD_DIARY12
    dw #ffff
    dw TEXT_VLAD_DIARY13
    dw TEXT_VLAD_DIARY14
    dw TEXT_VLAD_DIARY15
    dw TEXT_VLAD_DIARY16

vlad_diary_lines3:
    dw TEXT_VLAD_DIARY17
    dw TEXT_VLAD_DIARY18
    dw TEXT_VLAD_DIARY19
    dw TEXT_VLAD_DIARY20
    dw TEXT_VLAD_DIARY21

quincey_letter_lines:
    dw TEXT_QUINCEY_LETTER1
    dw TEXT_QUINCEY_LETTER2
    dw TEXT_QUINCEY_LETTER3
    dw TEXT_QUINCEY_LETTER4
    dw TEXT_QUINCEY_LETTER5
    dw TEXT_QUINCEY_LETTER6
    dw TEXT_QUINCEY_LETTER7
    dw TEXT_QUINCEY_LETTER8
    dw TEXT_QUINCEY_LETTER9
    dw #ffff
    dw TEXT_QUINCEY_LETTER10

franky_letter_lines:
    dw TEXT_FRANKY_LETTER1


map1_zx0:  ; entrance and east wing
    incbin "autogenerated/map1.zx0"

map2_zx0:  ; west wing
    incbin "autogenerated/map2.zx0"

map3_zx0:  ; catacombs
    incbin "autogenerated/map3.zx0"

map4_zx0:  ; top floor
    incbin "autogenerated/map4.zx0"

map5_zx0:  ; London
    incbin "autogenerated/map5.zx0"

map6_zx0:  ; sub-basement
    incbin "autogenerated/map6.zx0"

tiled_rooms_tiles_zx0:
    incbin "autogenerated/tiled-rooms/street1-tiles.zx0"
tiled_rooms_nametables_zx0:
    incbin "autogenerated/tiled-rooms/street-nametables.zx0"


street1_colliders:
    ; x, y, w, h
    db 0, 0, 40, 24
    db 0, 72, 24, 16
    db 0, 84, 40, 36
    db 0, 136, 40, 24
    db 144, 0, 8, 160
    db 0, 150, 160, 8
    db 0, 120, 36, 16
    db 40, 24, 8, 64

street2_colliders:
    ; x, y, w, h
    db 0, 0, 40, 160 
    db 0, 0, 160, 72
    db 0, 136, 160, 8

street3_colliders:
    ; x, y, w, h
    db 0, 0, 40, 160
    db 144, 0, 8, 160
    db 136, 144, 16, 16
    db 40,112, 2, 16
    db 0, 0, 160, 16


puzzle_altar_zx0:
    incbin "autogenerated/puzzle-altar.zx0"

puzzle_box_zx0:
    incbin "autogenerated/puzzle-box.zx0"

end_of_page_8:
    ds #c000 - $


;-----------------------------------------------
; PAGE 9: song bank 1
    org #a000
start_of_page_9:

MUSIC_INGAME_INTRO_PAGE: equ 9
MUSIC_INGAME_LONDON_PAGE: equ 9
MUSIC_INGAME_INTRO_ID: equ 2
MUSIC_INGAME_LONDON_ID: equ 3
music_intro:
music_ingame_london:
    incbin "autogenerated/music/London.mus"

MUSIC_INGAME_HOUSE1_PAGE: equ 9
MUSIC_INGAME_HOUSE1_ID: equ 4
music_ingame_house1:
    incbin "autogenerated/music/House_A.mus"

MUSIC_GAME_TITLE_PAGE: equ 9
MUSIC_GAME_TITLE_ID: equ  7
music_game_title:
    incbin "autogenerated/music/Westen_House_Title.mus"

; MUSIC_INGAME_FAMILY_CUTSCENE_PAGE: equ 9
; MUSIC_INGAME_FAMILY_CUTSCENE_ID: equ 12
; music_ingame_family_cutscene:
;     incbin "autogenerated/music/Cutscene1.mus"

MUSIC_INGAME_FAMILY_CUTSCENE_PAGE: equ 9
MUSIC_INGAME_FAMILY_CUTSCENE_ID: equ 12
MUSIC_RITUAL_CUTSCENE_PAGE: equ 9
MUSIC_RITUAL_CUTSCENE_ID: equ 21
music_ingame_ritual_cutscene:
music_ingame_family_cutscene:
    incbin "autogenerated/music/Cutscene3.mus"

MUSIC_ENDING_1A_PAGE: equ 9
MUSIC_ENDING_1A_ID: equ 22
music_ending_1a:
    incbin "autogenerated/music/Finale_1a.mus"

MUSIC_ENDING_1B_PAGE: equ 9
MUSIC_ENDING_1B_ID: equ 25
music_ending_1b:
    incbin "autogenerated/music/Finale_1b.mus"

MUSIC_ENDING_2_PAGE: equ 9
MUSIC_ENDING_2_ID: equ 26
music_ending_2:
    incbin "autogenerated/music/Finale_2.mus"


end_of_page_9:
    ds #c000 - $


;-----------------------------------------------
; PAGE 10: song bank 2
    org #a000
start_of_page_10:

MUSIC_INGAME_CELLAR_PAGE: equ 10
MUSIC_INGAME_CELLAR_ID: equ 9
music_ingame_cellar:
    incbin "autogenerated/music/Cellar1.mus"

MUSIC_INGAME_VAMPIRE_PAGE: equ 10
MUSIC_INGAME_VAMPIRE_ID: equ 11
music_ingame_vampire:
    incbin "autogenerated/music/Approaching_Coffin.mus"

MUSIC_LONDON_STREETS_PAGE: equ 10
MUSIC_LONDON_STREETS_ID: equ 15
music_london_streets:
;     incbin "autogenerated/music/London_Streets.mus"
    incbin "autogenerated/music/London_STREETS_V2.mus"

MUSIC_INGAME_TRAVEL_PAGE: equ 10
MUSIC_INGAME_TRAVEL_ID: equ 17
music_ingame_travel:
    incbin "autogenerated/music/Train_scene.mus"

MUSIC_GAME_START_PAGE: equ 10
MUSIC_GAME_START_ID: equ 1
music_game_start:
    incbin "autogenerated/music/Game_Start.mus"



SFX_jump:
    incbin  "../data/sfx/sfx0.afx"
SFX_ui_move:
    incbin  "../data/sfx/sfx1.afx"
SFX_ui_select:
    incbin  "../data/sfx/sfx2.afx"
SFX_door_open:
    incbin  "../data/sfx/sfx3.afx"
SFX_break_crate:
    incbin  "../data/sfx/sfx4.afx"
SFX_open_safe:
    incbin  "../data/sfx/sfx5.afx"
SFX_assemble_key:
    incbin  "../data/sfx/sfx6.afx"
SFX_use_heart:
    incbin  "../data/sfx/sfx7.afx"
SFX_lever:
SFX_puzzle_solved:
    incbin  "../data/sfx/sfx8.afx"
SFX_playerhit:
    incbin  "../data/sfx/sfx9.afx"
SFX_explosion:
    incbin  "../data/sfx/sfx10.afx"
SFX_arrow:
    incbin  "../data/sfx/sfx11.afx"
SFX_enemy_hit:
    incbin  "../data/sfx/sfx12.afx"
SFX_enemy_death:
    incbin  "../data/sfx/sfx13.afx"
SFX_use_stake:
    incbin  "../data/sfx/sfx14.afx"
SFX_beggar_scream:
    incbin  "../data/sfx/sfx15.afx"
SFX_jaaaames:
    incbin  "../data/sfx/sfx16.afx"
SFX_doorbell:
    incbin  "../data/sfx/sfx17.afx"
SFX_ui_change_letter:
    incbin  "../data/sfx/sfx18.afx"
SFX_push_objects:
    incbin  "../data/sfx/sfx19.afx"


end_of_page_10:
    ds #c000 - $    

;-----------------------------------------------
; PAGE 11: song bank 3
    org #a000
start_of_page_11:

MUSIC_INGAME_SUBBASEMENT_PAGE: equ 11
MUSIC_INGAME_SUBBASEMENT_ID: equ 14
music_ingame_subbasement:
    incbin "autogenerated/music/Danger_B.mus"

MUSIC_RIDDLE_SOLVED_PAGE: equ 11
MUSIC_RIDDLE_SOLVED_ID: equ 19
music_riddle_solved:
    incbin "autogenerated/music/Riddle_Solved.mus"

MUSIC_BOSS_A_PAGE: equ 11
MUSIC_BOSS_A_ID: equ 23
music_boss_a:
    incbin "autogenerated/music/Boss_A.mus"

MUSIC_INGAME_HOUSE2_PAGE: equ 11
MUSIC_INGAME_HOUSE2_ID: equ 5
music_ingame_house2:
    incbin "autogenerated/music/House_B.mus"

MUSIC_INGAME_SUBBASEMENT2_PAGE: equ 11
MUSIC_INGAME_SUBBASEMENT2_ID: equ 20
music_ingame_subbasement2:
    incbin "autogenerated/music/Danger_A.mus"


end_of_page_11:
    ds #c000 - $

;-----------------------------------------------
; PAGE 12: song bank 4 + SFX
    org #a000
start_of_page_12:

MUSIC_RIDDLE_SOLVING_PAGE: equ 12
MUSIC_RIDDLE_SOLVING_ID: equ 18
music_riddle_solving:
    incbin "autogenerated/music/Riddle_Solving.mus"

MUSIC_BOSS_B_PAGE: equ 12
MUSIC_BOSS_B_ID: equ 24
music_boss_b:
    incbin "autogenerated/music/Boss_B.mus"

MUSIC_INGAME_HOUSE_YARD_PAGE: equ 12
MUSIC_INGAME_HOUSE_YARD_ID: equ 16
music_ingame_house_yard:
    incbin "autogenerated/music/Garden_entrance.mus"

MUSIC_GAME_OVER_PAGE: equ 12
MUSIC_GAME_OVER_ID: equ 6
music_game_over:
    incbin "autogenerated/music/1UP_Death.mus"

MUSIC_INGAME_HOUSE3_PAGE: equ 12
MUSIC_INGAME_HOUSE3_ID: equ 8
music_ingame_house3:
    incbin "autogenerated/music/House_C.mus"

MUSIC_INGAME_CELLAR15_PAGE: equ 12
MUSIC_INGAME_CELLAR15_ID: equ 10
music_ingame_cellar15:
    incbin "autogenerated/music/Cellar1.5.mus"

MUSIC_INGAME_LUCY_CUTSCENE_PAGE: equ 12
MUSIC_INGAME_LUCY_CUTSCENE_ID: equ 13
music_ingame_lucy_cutscene:
    incbin "autogenerated/music/Cutscene2.mus"

end_of_page_12:
    ds #c000 - $

;-----------------------------------------------
; PAGE 13: text (english)
    org #a000
start_of_page_13:


textBankPointers_en:
    dw textBank0_en
    dw textBank1_en
    dw textBank2_en
    dw textBank3_en
    dw textBank4_en
    dw textBank5_en
    dw textBank6_en
    dw textBank7_en
    dw textBank8_en
    dw textBank9_en
    dw textBank10_en
    dw textBank11_en
    dw textBank12_en
    dw textBank13_en
    dw textBank14_en
    dw textBank15_en
    dw textBank16_en
    dw textBank17_en
    dw textBank18_en
    dw textBank19_en
    dw textBank20_en


textBank0_en:
    incbin "autogenerated/textBank0.zx0"
textBank1_en:
    incbin "autogenerated/textBank1.zx0"
textBank2_en:
    incbin "autogenerated/textBank2.zx0"
textBank3_en:
    incbin "autogenerated/textBank3.zx0"
textBank4_en:
    incbin "autogenerated/textBank4.zx0"
textBank5_en:
    incbin "autogenerated/textBank5.zx0"
textBank6_en:
    incbin "autogenerated/textBank6.zx0"
textBank7_en:
    incbin "autogenerated/textBank7.zx0"
textBank8_en:
    incbin "autogenerated/textBank8.zx0"
textBank9_en:
    incbin "autogenerated/textBank9.zx0"
textBank10_en:
    incbin "autogenerated/textBank10.zx0"
textBank11_en:
    incbin "autogenerated/textBank11.zx0"
textBank12_en:
    incbin "autogenerated/textBank12.zx0"
textBank13_en:
    incbin "autogenerated/textBank13.zx0"
textBank14_en:
    incbin "autogenerated/textBank14.zx0"
textBank15_en:
    incbin "autogenerated/textBank15.zx0"
textBank16_en:
    incbin "autogenerated/textBank16.zx0"
textBank17_en:
    incbin "autogenerated/textBank17.zx0"
textBank18_en:
    incbin "autogenerated/textBank18.zx0"
textBank19_en:
    incbin "autogenerated/textBank19.zx0"
textBank20_en:
    incbin "autogenerated/textBank20.zx0"

end_of_page_13:
    ds #c000 - $

;-----------------------------------------------
; PAGE 14: graphic data
    org #a000
start_of_page_14:

;-----------------------------------------------
; Graphics:
; floor_blue_tiles_zx0:
;     incbin "autogenerated/floor-blue-tiles.zx0"
floor_grass_zx0:
    incbin "autogenerated/floor-grass.zx0"
floor_blue_tiles_border_zx0:
    incbin "autogenerated/floor-blue-tiles-border.zx0"
floor_wood_zx0:
    incbin "autogenerated/floor-wood.zx0"
floor_white_tiles_border_zx0:
    incbin "autogenerated/floor-white-tiles-border.zx0"

wall_bookshelves_zx0:
    incbin "autogenerated/wall-bookshelves.zx0"
wall_bluebricks_zx0:
    incbin "autogenerated/wall-blue-bricks.zx0"
wall_entrance_zx0:
    incbin "autogenerated/wall-entrance.zx0"
wall_victorian_zx0:
    incbin "autogenerated/wall-victorian.zx0"
wall_bricks_bookshelves_zx0:
    incbin "autogenerated/wall-bricks-shelves.zx0"
wall_ossuary_zx0:
    incbin "autogenerated/wall-ossuary.zx0"
wall_white_stone_zx0:
    incbin "autogenerated/wall-white-stone.zx0"

door_left_brick_zx0:
    incbin "autogenerated/door-left-brick.zx0"
door_left_brick_stairs_zx0:
    incbin "autogenerated/door-left-brick-stairs.zx0"
door_right_brick_zx0:
    incbin "autogenerated/door-right-brick.zx0"
door_right_brick_stairs_zx0:
    incbin "autogenerated/door-right-brick-stairs.zx0"
door_left_bookshelf_zx0:
    incbin "autogenerated/door-left-bookshelf.zx0"
door_right_bookshelf_zx0:
    incbin "autogenerated/door-right-bookshelf.zx0"
door_right_entrance_zx0:
    incbin "autogenerated/door-right-entrance.zx0"
door_sw_zx0:
    incbin "autogenerated/door-sw.zx0"
door_se_zx0:
    incbin "autogenerated/door-se.zx0"
door_wood_nw_zx0:
    incbin "autogenerated/door-wood-nw.zx0"
door_wood_ne_zx0:
    incbin "autogenerated/door-wood-ne.zx0"
door_wood_sw_zx0:
    incbin "autogenerated/door-wood-sw.zx0"
door_wood_se_zx0:
    incbin "autogenerated/door-wood-se.zx0"
door_victorian_tiles_nw_zx0:
    incbin "autogenerated/door-victorian-tiles-nw.zx0"
door_victorian_tiles_ne_zx0:
    incbin "autogenerated/door-victorian-tiles-ne.zx0"
door_gothic_nw_zx0:
    incbin "autogenerated/door-gothic-nw.zx0"
door_gothic_ne_zx0:
    incbin "autogenerated/door-gothic-ne.zx0"
door_gothic_sw_zx0:
    incbin "autogenerated/door-gothic-sw.zx0"
door_gothic_se_zx0:
    incbin "autogenerated/door-gothic-se.zx0"


inventory_tiles_ptrs:
    dw inventory_tiles0_zx0
    dw inventory_tiles1_zx0
    dw inventory_tiles2_zx0

inventory_tiles0_zx0:
    incbin "autogenerated/inventory0.zx0"
inventory_tiles1_zx0:
    incbin "autogenerated/inventory1.zx0"
inventory_tiles2_zx0:
    incbin "autogenerated/inventory2.zx0"

enemy_rat_zx0:
    incbin "autogenerated/enemies/rat.zx0"
enemy_spider_zx0:
    incbin "autogenerated/enemies/spider.zx0"
enemy_slime_zx0:
    incbin "autogenerated/enemies/slime.zx0"
enemy_bat_zx0:
    incbin "autogenerated/enemies/bat.zx0"
enemy_snake_zx0:
    incbin "autogenerated/enemies/snake.zx0"
enemy_arrow_zx0:
    incbin "autogenerated/enemies/arrow.zx0"


;-----------------------------------------------
; Graphics:
hud_zx0:
;     incbin "autogenerated/hud.zx0"
    incbin "autogenerated/hud-ex.zx0"

title_zx0:
    incbin "autogenerated/title.zx0"

braingames_zx0:
    incbin "autogenerated/braingames.zx0"

tutorial_zx0:
    incbin "autogenerated/tutorial.zx0"

password_lock_zx0:
    incbin "autogenerated/password-lock.zx0"

end_of_page_14:
    ds #c000 - $

; ;-----------------------------------------------
; PAGE 15: text (spanish)
    org #a000
start_of_page_15:


textBankPointers_es:
    dw textBank0_es
    dw textBank1_es
    dw textBank2_es
    dw textBank3_es
    dw textBank4_es
    dw textBank5_es
    dw textBank6_es
    dw textBank7_es
    dw textBank8_es
    dw textBank9_es
    dw textBank10_es
    dw textBank11_es
    dw textBank12_es
    dw textBank13_es
    dw textBank14_es
    dw textBank15_es
    dw textBank16_es
    dw textBank17_es
    dw textBank18_es
    dw textBank19_es
    dw textBank20_es


textBank0_es:
    incbin "autogenerated/textBank-es0.zx0"
textBank1_es:
    incbin "autogenerated/textBank-es1.zx0"
textBank2_es:
    incbin "autogenerated/textBank-es2.zx0"
textBank3_es:
    incbin "autogenerated/textBank-es3.zx0"
textBank4_es:
    incbin "autogenerated/textBank-es4.zx0"
textBank5_es:
    incbin "autogenerated/textBank-es5.zx0"
textBank6_es:
    incbin "autogenerated/textBank-es6.zx0"
textBank7_es:
    incbin "autogenerated/textBank-es7.zx0"
textBank8_es:
    incbin "autogenerated/textBank-es8.zx0"
textBank9_es:
    incbin "autogenerated/textBank-es9.zx0"
textBank10_es:
    incbin "autogenerated/textBank-es10.zx0"
textBank11_es:
    incbin "autogenerated/textBank-es11.zx0"
textBank12_es:
    incbin "autogenerated/textBank-es12.zx0"
textBank13_es:
    incbin "autogenerated/textBank-es13.zx0"
textBank14_es:
    incbin "autogenerated/textBank-es14.zx0"
textBank15_es:
    incbin "autogenerated/textBank-es15.zx0"
textBank16_es:
    incbin "autogenerated/textBank-es16.zx0"
textBank17_es:
    incbin "autogenerated/textBank-es17.zx0"
textBank18_es:
    incbin "autogenerated/textBank-es18.zx0"
textBank19_es:
    incbin "autogenerated/textBank-es19.zx0"
textBank20_es:
    incbin "autogenerated/textBank-es20.zx0"


end_of_page_15:
    ds #c000 - $
; end_of_page_15:
;     ds (#c000 - (konami_mark_end - konami_mark_start)) - $

; Fake Konami title and RC number :) (see https://msx.org/forum/msx-talk/software/some-konami-roms-include-the-game-title-and-rc-number)
; konami_mark_start:
;     db "EX ESUOH NETSEW",#0f,#67,#AA
; konami_mark_end:


;-----------------------------------------------
; RAM:
    org #c000   ; RAM goes to the 4th page
RAM:
row_draw_buffer:
buffer1024:                 ds virtual 1024

text_decompression_buffer:  equ buffer1024
text_draw_buffer:           equ text_decompression_buffer + TEXT_BANK_SIZE  ; 32*8 = 256 (enough to draw a full screen width of text)
text_buffer:                equ text_draw_buffer + 256  ; buffer to store decompressed text before rendering

enemy_data_buffer:          ds virtual 4*2*4*96 ; 4 directions * 2 frames * 4 offsets * 96 (24x16 sprites with mask-pattern bytes)
                                                ; 3072 bytes

floor_data_buffer:          ds virtual 13*16
wall_data_buffer:           ds virtual 780
object_decompression_buffer:    ds virtual OBJECT_DECOMPRESSION_BUFFER_SIZE
door_decompression_buffer:  ds virtual DOOR_DECOMPRESSION_BUFFER_SIZE

; These two variables share space, as they are never used at the same time:
last_decompressed_inventory_bank:
last_decompressed_text_bank:    ds virtual 1

; General variables:
ROM_slot:                   ds virtual 1        ; slot where the game was inserted
isComputer50HzOr60Hz:       ds virtual 1        ; 0: 50Hz, 1: 60Hz
current_language_page:      ds virtual 1
current_language_table:     ds virtual 2
current_language_bank_ptr:  ds virtual 2
current_megarom_page_in_8000: ds virtual 1
current_megarom_page_in_a000: ds virtual 1
interrupt_cycle:            ds virtual 1
interrupt_tempo_state:      ds virtual 1        ; at each cycle, we will add "(interrupt_tempo_speed)" to this,
interrupt_tempo_speed:      ds virtual 1        ; each time there is a carry over, there is an interrupt
; randSeedIndex:              ds virtual 1
; randData:                   ds virtual 2
key_to_direction_mapping_ptr:   ds virtual 2

; Room variables:
room_x:                     ds virtual 1
room_y:                     ds virtual 1
room_width:                 ds virtual 1
room_height:                ds virtual 1
room_width_pixels:          ds virtual 1
room_height_pixels:         ds virtual 1
background_tile_ptrs:       ds virtual 32*SCREEN_HEIGHT*2

n_doors:                    ds virtual 1
doors:                      ds virtual DOOR_STRUCT_SIZE*MAX_ROOM_DOORS

n_objects:                  ds virtual 1
objects:                    ds virtual OBJECT_STRUCT_SIZE*MAX_ROOM_OBJECTS

n_collision_objects:        ds virtual 1
collision_objects:          ds virtual OBJECT_STRUCT_SIZE*MAX_ROOM_COLLISION_OBJECTS

; rendering variables:
render_room_rectangle_xy:   ds virtual 2
render_room_rectangle_wh:   ds virtual 2
render_room_object_screen_pixel_h:   ds virtual 1

player_sprite_attributes:   ds virtual 4*6
inventory_pointer_sprite_attributes: ds virtual 4

player_sprite_occlusion_buffer: ds virtual 2*OCCLUSION_MASK_HEIGHT

room_enemy_type:            ds virtual 1

ram_to_clear_at_game_start:
keyboard_line_state:        ds virtual 1  ; interleaved bytes state/clicks
keyboard_line_clicks:       ds virtual 3
keyboard_line_state_prev:   ds virtual 2
game_cycle:                 ds virtual 1

hud_messages:               ds virtual 2*MAX_HUD_MESSAGES
hud_message_timer:          ds virtual 1
hud_message_queue:          ds virtual 2*HUD_MESSAGE_QUEUE_SIZE
hud_message_queue_size:     ds virtual 1
draw_hud_chunk_tile_ptr:    ds virtual 2

inventory_first_displayed_item:       ds virtual 1  ; 0 for starting to draw in the first row, or INVENTORY_ROW_SIZE to start in the second row
inventory_selected:         ds virtual 1  ; out of the ones currently seen in screen
gun_cooldown:               ds virtual 1
current_room_vampire_state: ds virtual 1  ; 0 sleeping, 1: awake, 2: has seen player (and spawned a bat)
miniboss_hit:
snake_already_attacking:    ds virtual 1  ; only one snake can dash at a time to prevent slow-downs
miniboss_hitpoints:         ds virtual 1


call_james_when_hud_messages_done: ds virtual 1

game_state_start:
player_direction:           ds virtual 1
player_state:               ds virtual 1
player_state_timer:         ds virtual 1
player_iso_x:               ds virtual 1
player_iso_y:               ds virtual 1
player_iso_z:               ds virtual 1
player_iso_w:               ds virtual 1
player_iso_h:               ds virtual 1
player_iso_z_h              ds virtual 1
player_screen_x:            ds virtual 1
player_screen_y:            ds virtual 1
player_health:              ds virtual 1
player_max_health:          ds virtual 1
player_invulnerability:     ds virtual 1    
inventory:                  ds virtual INVENTORY_SIZE    
state_game_time_day:        ds virtual 1
state_current_room:         ds virtual 1
state_yellow_key_taken:     ds virtual 1  ; 0: not taken, 1: taken, 2: used
state_white_key_taken:      ds virtual 1  ; 0: not taken, 1: taken, 2: used
state_red_key_taken:        ds virtual 1  ; 0: not taken, 1: taken, 2: used
state_green_key_taken:      ds virtual 1  ; 0: not taken, 1: taken, 2: used
state_backyard_key_taken:   ds virtual 1  ; 0: not taken, 1: taken, 2: used
state_gun_taken:            ds virtual 1
state_letter3_taken:        ds virtual 1  ; 0: not taken, 1: taken, 2: read, 3: code developed, 4: code seen, 5: code used
state_lamp_taken:           ds virtual 1
state_oil_taken:            ds virtual 1
state_painting_safe:        ds virtual 1
state_heart1_taken:         ds virtual 1
state_heart2_taken:         ds virtual 1
state_heart3_taken:         ds virtual 1
state_heart4_taken:         ds virtual 1
state_book_taken:           ds virtual 1
state_diary1_taken:         ds virtual 1
state_diary2_taken:         ds virtual 1
state_diary3_taken:         ds virtual 1
state_candle1_position:     ds virtual 4  ; room, x, y, z
state_candle2_position:     ds virtual 4
state_candle3_position:     ds virtual 4
state_writing_room_msg:     ds virtual 1
state_ritual_room_state:    ds virtual 1  ; 0: not found, 1: found, 2: solved (1st pattrn), 3: solved (2nd pattern)
state_hammer_taken:         ds virtual 1  ; 0: not taken, 1: taken
state_crate_garlic1:        ds virtual 1  ; 0: not broken, 1: broken, 2: item taken
state_crate_garlic2:        ds virtual 1  ; 0: not broken, 1: broken, 2: item taken
state_crate_garlic3:        ds virtual 1  ; 0: not broken, 1: broken, 2: item taken    
state_crate_stake1:         ds virtual 1  ; 0: not broken, 1: broken, 2: item taken
state_crate_stake2:         ds virtual 1  ; 0: not broken, 1: broken, 2: item taken
state_crate_stake3:         ds virtual 1  ; 0: not broken, 1: broken, 2: item taken
state_lab_notes_taken:      ds virtual 1  ; 0: not taken, 1: taken, 2: used
state_vampire1_state:       ds virtual 1  ; 0: door closed, 1: door open, 2: killed
state_vampire2_state:       ds virtual 1  ; 0: door closed, 1: door open, 2: killed
state_vampire3_state:       ds virtual 1  ; 0: door closed, 1: door open, 2: killed
state_vampire4_state:       ds virtual 1  ; 0: door closed, 1: door open
state_luggage_taken:        ds virtual 1
state_newspaper_taken:      ds virtual 1
state_beggar:               ds virtual 1  ; 0: init, 1: talked to once, 2: talked to twice, 3: dead
state_choffeur_store:       ds virtual 1  ; 0: choffeur sleeping, 1: awake, 2: book found, 3: book purchased
state_torn_note_taken:      ds virtual 1
state_reached_subbasement:  ds virtual 1
state_puzzle_box_taken:     ds virtual 1  ; 0: not taken, 1: taken, 2: attempted, 3: solved
state_vlad_statue_examined: ds virtual 1     
state_vlad_diary_taken:     ds virtual 1
state_reveal_clue_taken:    ds virtual 1
state_mirrors_broken:       ds virtual 1  ; each bit represents one mirror
state_cutlery_taken:        ds virtual 1
state_prison_door_entrance: ds virtual 1
state_cauldron_taken:       ds virtual 1
state_switches:             ds virtual 1  ; 1 bit per switch: prison1, prison2, boss1, -, -, -, -, -
state_shovel_taken:         ds virtual 1
state_skeleton_miniboss:    ds virtual 1  ; 0 not killed, 1: killed
state_skeleton_key_taken:   ds virtual 1
state_quincey_grave:        ds virtual 1  ; 0 not dug, 1: key taken, 2: key used, 3: dug, key not taken
state_clay_taken:           ds virtual 1
state_franky_key_taken:     ds virtual 1
state_quincey_note_read:    ds virtual 1
state_franky_boss:          ds virtual 1  ; 0 not killed, 1: killed, note not taken, 2: note taken
game_state_end:

ram_to_clear_at_game_start_end:

current_music:        ds virtual 1  ; 0: nothing, 1: intro, etc.
current_music_page:   ds virtual 1     

; temporary variables:
door_collider_generation_position_x:  equ buffer1024
door_collider_generation_position_y:  equ buffer1024+1
door_collider_generation_door_type: equ buffer1024+2
door_collider_generation_collided_door_type: equ buffer1024+3
update_object_drawing_order_any_change: equ buffer1024
continue_yes_no:            equ room_enemy_type
language_selection_pos:     equ room_enemy_type

; puzzle variables:
puzzle_pointer_sprite_attributes: ds virtual 4
puzzle_pointer_position:    ds virtual 1
puzzle_current_letters:     ds virtual CHAPEL_PUZZLE_MESSAGE_LEN
puzzle_tmp_string_buffer:   ds virtual 2


; ending variables:
ending_trigger_map:             ds virtual 1  ; 0/1: map 1 triggered/loaded 2/3: map 2; 4/5: map 3
ending_roll_step:               ds virtual 1  ; from 3-21: unrolling, from 103-121: rolling, 128: reset
ending_text_page_line_state:    ds virtual 1  ; 0: we still need to draw it, > 0 we are displaying it
ending_text_page:               ds virtual 1  ; 0 (text 1), 1 (wait), 2 (text 2), 3 (wait), 4 (the end)
ending_text_page_line:          ds virtual 1
ending_music_sync_pause:        ds virtual 1  ; contains "5" if we are in a 60hz machine and "4" for 50hz machines to sync with the music.

; save game:
RAM_game_saved:                 ds virtual 1
RAM_save:                       ds virtual (game_state_end - game_state_start)

;     include "wyzplayer47c-RAM.asm"
    include "wyzplayer47d-RAM.asm"

; SFX player variables (PSG registers that overwrite those set by the wyz player):
; - registers 2, 3, 6, 7 and 9
SFX_player_registers:   ds virtual 5
SFX_player_active: ds virtual 1
SFX_player_pointer: ds virtual 2

END_OF_RAM:

